const en = {
  saveNext: 'Save for next run', apply: 'Apply', restart: 'Apply & restart', switchStart: 'Switch & start',
  profilePending: 'Save or discard the shared profile edits before applying the target settings.', pathPending: 'Select the entered model path before applying.',
  details: 'Model settings', choose: 'Choose model',
  title: 'Model & settings', model: 'Model', runtime: 'Runtime & GPU', tuning: 'Performance & memory', sampling: 'Generation', reasoning: 'Reasoning', adapters: 'Auxiliary models & LoRA', advanced: 'Advanced', profiles: 'Profiles',
  search: 'Search models', path: 'Model path', selected: 'Selected', empty: 'No matching models. Enter a model path or manage the model folder.', refresh: 'Refresh', browse: 'Choose file',
  draft: 'Changes stay in this editor until you apply them.', save: 'Save selection & settings', start: 'Save & start', benchmarkApply: 'Apply to benchmark', projectApply: 'Apply to project editor', cancel: 'Cancel', close: 'Close',
  discardTitle: 'Discard unsaved changes?', discardBody: 'Your changes in this editor have not been applied.', discard: 'Discard changes', keep: 'Keep editing',
  pending: 'Applying…', benchmarkControlled: 'Context size, concurrency, timeout and sampling are determined by the benchmark workloads. Chat prompts and request settings are not used.',
  systemRuntime: 'System runtime (PATH)', manageRuntime: 'Manage runtimes', missingRuntime: 'The selected runtime is not installed. You can save these settings, but install the runtime before starting.',
  reset: 'Reset to runtime defaults', preset: 'Load preset', balanced: 'Balanced', cpu: 'CPU', maxGpu: 'Max GPU', tuningProfile: 'Load model tuning profile',
  invalid: 'Correct invalid fields before applying.', rawArgs: 'Extra server arguments (one per line)', rawChat: 'Extra request JSON',
  projector: 'Vision projector', draftModel: 'Draft model', none: 'None', addLora: 'Add LoRA file', scale: 'Scale', enabled: 'Enabled', remove: 'Remove',
  shared: 'Shared profile management', sharedHint: 'Shared profiles have separate Save and Delete actions. Completed changes remain even if you cancel this model settings editor.',
  load: 'Load into editor', saveProfile: 'Save shared profile', newProfile: 'Save as new profile', deleteProfile: 'Delete shared profile', profileName: 'Profile name', serverProfile: 'Server profile', modelProfile: 'Generation profile', prompt: 'Default system prompt', stop: 'Stop strings (one per line)', profileSaved: 'Shared profile saved.', profileDeleted: 'Shared profile deleted.', profileDeleteConfirm: 'Delete this shared profile?',
  gpu: 'GPU placement', automatic: 'Automatic', tensorSplit: 'Tensor split (comma-separated weights)', truncated: 'The model list was truncated. Narrow the model folder or enter a path.',
  options: 'Runtime options', optionSearch: 'Search runtime options', optionApply: 'Update editor', unavailable: 'Unavailable',
};
type Copy = { [K in keyof typeof en]: string };
const ko: Copy = {
  saveNext: '다음 실행에 저장', apply: '적용', restart: '적용 후 다시 실행', switchStart: '전환하여 실행',
  profilePending: '공유 프로필 편집을 저장하거나 버린 뒤 대상 설정을 적용하세요.', pathPending: '입력한 모델 경로를 선택한 뒤 적용하세요.',
  details: '모델 설정', choose: '모델 선택',
  title: '모델 선택·설정', model: '모델', runtime: '런타임·GPU', tuning: '성능·메모리', sampling: '생성', reasoning: '추론', adapters: '보조 모델·LoRA', advanced: '고급', profiles: '프로필',
  search: '모델 검색', path: '모델 경로', selected: '선택됨', empty: '일치하는 모델이 없습니다. 모델 경로를 입력하거나 모델 폴더를 관리하세요.', refresh: '새로고침', browse: '파일 선택',
  draft: '적용하기 전까지 변경 사항은 이 편집기에만 보관됩니다.', save: '선택 및 설정 저장', start: '저장 후 실행', benchmarkApply: '벤치마크에 적용', projectApply: '프로젝트 편집에 적용', cancel: '취소', close: '닫기',
  discardTitle: '편집 중인 변경을 버릴까요?', discardBody: '이 편집기의 변경 사항은 아직 적용되지 않았습니다.', discard: '변경 버리기', keep: '계속 편집', pending: '적용 중…',
  benchmarkControlled: '컨텍스트 크기·동시 요청 수·시간 제한·샘플링은 벤치마크 측정 조건에서 결정합니다. 채팅 프롬프트와 요청 설정은 사용하지 않습니다.',
  systemRuntime: '시스템 런타임 (PATH)', manageRuntime: '런타임 관리', missingRuntime: '선택한 런타임이 설치되지 않았습니다. 설정은 저장할 수 있지만 실행 전에 런타임을 설치해야 합니다.',
  reset: '런타임 기본값으로 초기화', preset: '프리셋 불러오기', balanced: '균형', cpu: 'CPU', maxGpu: '최대 GPU', tuningProfile: '모델 튜닝 프로필 불러오기',
  invalid: '잘못 입력된 항목을 수정한 뒤 적용하세요.', rawArgs: '추가 서버 인자 (한 줄에 하나)', rawChat: '추가 요청 JSON',
  projector: '비전 프로젝터', draftModel: '초안 모델', none: '없음', addLora: 'LoRA 파일 추가', scale: '배율', enabled: '사용', remove: '제거',
  shared: '공유 프로필 관리', sharedHint: '공유 프로필은 별도의 저장·삭제 버튼으로 반영합니다. 완료한 변경은 모델 설정 편집기를 취소해도 유지됩니다.',
  load: '편집기에 불러오기', saveProfile: '공유 프로필 저장', newProfile: '새 프로필로 저장', deleteProfile: '공유 프로필 삭제', profileName: '프로필 이름', serverProfile: '서버 프로필', modelProfile: '생성 프로필', prompt: '기본 시스템 프롬프트', stop: '중지 문자열 (한 줄에 하나)', profileSaved: '공유 프로필을 저장했습니다.', profileDeleted: '공유 프로필을 삭제했습니다.', profileDeleteConfirm: '이 공유 프로필을 삭제할까요?',
  gpu: 'GPU 배치', automatic: '자동', tensorSplit: '텐서 분할 (쉼표로 구분한 비중)', truncated: '모델 목록이 일부만 표시됩니다. 모델 폴더 범위를 줄이거나 경로를 입력하세요.',
  options: '런타임 옵션', optionSearch: '런타임 옵션 검색', optionApply: '편집기에 반영', unavailable: '사용 불가',
};
const ja: Copy = {
  saveNext: '次回の起動用に保存', apply: '適用', restart: '適用して再起動', switchStart: '切り替えて起動',
  profilePending: '共有プロファイルの編集を保存または破棄してから対象の設定を適用してください。', pathPending: '入力したモデルパスを選択してから適用してください。',
  details: 'モデル設定', choose: 'モデルを選択',
  title: 'モデル選択・設定', model: 'モデル', runtime: 'ランタイム・GPU', tuning: '性能・メモリ', sampling: '生成', reasoning: '推論', adapters: '補助モデル・LoRA', advanced: '詳細', profiles: 'プロファイル',
  search: 'モデルを検索', path: 'モデルパス', selected: '選択中', empty: '一致するモデルがありません。パスを入力するかモデルフォルダーを管理してください。', refresh: '更新', browse: 'ファイルを選択',
  draft: '適用するまで変更はこのエディター内に保持されます。', save: '選択と設定を保存', start: '保存して起動', benchmarkApply: 'ベンチマークに適用', projectApply: 'プロジェクト編集に適用', cancel: 'キャンセル', close: '閉じる',
  discardTitle: '未保存の変更を破棄しますか？', discardBody: 'このエディターの変更はまだ適用されていません。', discard: '変更を破棄', keep: '編集を続ける', pending: '適用中…',
  benchmarkControlled: 'コンテキスト、同時リクエスト数、タイムアウト、サンプリングは測定条件で決まります。チャットのプロンプトとリクエスト設定は使用しません。',
  systemRuntime: 'システムランタイム (PATH)', manageRuntime: 'ランタイム管理', missingRuntime: '選択したランタイムは未インストールです。設定は保存できますが起動前にインストールしてください。',
  reset: 'ランタイム既定値に戻す', preset: 'プリセットを読み込む', balanced: 'バランス', cpu: 'CPU', maxGpu: '最大 GPU', tuningProfile: 'モデルの調整プロファイルを読み込む',
  invalid: '無効な項目を修正してから適用してください。', rawArgs: '追加サーバー引数（1行に1つ）', rawChat: '追加リクエスト JSON',
  projector: '画像プロジェクター', draftModel: 'ドラフトモデル', none: 'なし', addLora: 'LoRA ファイルを追加', scale: '倍率', enabled: '有効', remove: '削除',
  shared: '共有プロファイル管理', sharedHint: '共有プロファイルは専用の保存・削除操作で反映します。完了した変更はモデル設定をキャンセルしても保持されます。',
  load: 'エディターに読み込む', saveProfile: '共有プロファイルを保存', newProfile: '新規プロファイルとして保存', deleteProfile: '共有プロファイルを削除', profileName: 'プロファイル名', serverProfile: 'サーバープロファイル', modelProfile: '生成プロファイル', prompt: '既定のシステムプロンプト', stop: '停止文字列（1行に1つ）', profileSaved: '共有プロファイルを保存しました。', profileDeleted: '共有プロファイルを削除しました。', profileDeleteConfirm: 'この共有プロファイルを削除しますか？',
  gpu: 'GPU 配置', automatic: '自動', tensorSplit: 'テンソル分割（カンマ区切りの重み）', truncated: 'モデル一覧が省略されています。フォルダーを絞るかパスを入力してください。', options: 'ランタイムオプション', optionSearch: 'オプションを検索', optionApply: 'エディターを更新', unavailable: '利用不可',
};
const zh: Copy = {
  saveNext: '保存供下次运行', apply: '应用', restart: '应用并重启', switchStart: '切换并启动',
  profilePending: '请先保存或放弃共享预设编辑，再应用目标设置。', pathPending: '请先选择输入的模型路径，再应用设置。',
  details: '模型设置', choose: '选择模型',
  title: '模型选择与设置', model: '模型', runtime: '运行时与 GPU', tuning: '性能与内存', sampling: '生成', reasoning: '推理', adapters: '辅助模型与 LoRA', advanced: '高级', profiles: '配置预设',
  search: '搜索模型', path: '模型路径', selected: '已选择', empty: '没有匹配的模型。请输入路径或管理模型目录。', refresh: '刷新', browse: '选择文件',
  draft: '应用前，修改仅保留在此编辑器中。', save: '保存选择与设置', start: '保存并启动', benchmarkApply: '应用到基准测试', projectApply: '应用到项目编辑', cancel: '取消', close: '关闭',
  discardTitle: '放弃未保存的修改？', discardBody: '此编辑器中的修改尚未应用。', discard: '放弃修改', keep: '继续编辑', pending: '正在应用…',
  benchmarkControlled: '上下文大小、并发请求数、超时和采样由测试条件决定。不使用聊天提示词和请求设置。',
  systemRuntime: '系统运行时 (PATH)', manageRuntime: '管理运行时', missingRuntime: '所选运行时尚未安装。可以保存设置，但启动前需要安装运行时。',
  reset: '恢复运行时默认值', preset: '加载预设', balanced: '均衡', cpu: 'CPU', maxGpu: '最大 GPU', tuningProfile: '加载模型调优预设',
  invalid: '请修正无效项目后再应用。', rawArgs: '附加服务器参数（每行一个）', rawChat: '附加请求 JSON',
  projector: '视觉投影器', draftModel: '草稿模型', none: '无', addLora: '添加 LoRA 文件', scale: '倍率', enabled: '启用', remove: '移除',
  shared: '共享预设管理', sharedHint: '共享预设通过单独的保存和删除操作生效。即使取消模型设置编辑器，已完成的修改也会保留。',
  load: '加载到编辑器', saveProfile: '保存共享预设', newProfile: '另存为新预设', deleteProfile: '删除共享预设', profileName: '预设名称', serverProfile: '服务器预设', modelProfile: '生成预设', prompt: '默认系统提示词', stop: '停止字符串（每行一个）', profileSaved: '已保存共享预设。', profileDeleted: '已删除共享预设。', profileDeleteConfirm: '删除此共享预设？',
  gpu: 'GPU 分配', automatic: '自动', tensorSplit: '张量分割（逗号分隔权重）', truncated: '模型列表已截断。请缩小模型目录范围或输入路径。', options: '运行时选项', optionSearch: '搜索运行时选项', optionApply: '更新编辑器', unavailable: '不可用',
};
export const modelSettingsCopy = { en, ko, ja, zh };
export type ModelSettingsCopy = Copy;
