const en = {
  saveConfirmAction: 'Save changes',
  saveConfirmTitle: 'Save these changes to “{name}”?', saveConfirmUnchanged: 'Nothing in this profile would change.',
  pasteLabel: 'Apply a llama-server command', pasteHint: 'Paste a command from a model card or a forum post; its flags are read into the controls below. Line continuations and quoted paths are understood.', pastePlaceholder: '-c 131072 -ngl 999 -fa on --temp 0.7', pasteApply: 'Apply pasted settings', pasteApplied: 'Applied {count} settings.', pasteRejected: 'Not applied:', pasteUnknown: 'this app has no setting for it', pasteMissing: 'no value was given', pasteBadValue: 'outside the accepted range',
  restart: 'Save profile & restart', switchStart: 'Save profile, switch & start',
  projectPromptHint: 'Edit and save this prompt in the profile’s model settings.',
  profileInUse: 'The running model was started from this profile. Stop it, or save to another profile, to change these settings.', profilePending: 'Finish or cancel the profile action before saving.', pathPending: 'Select the entered model path before saving.',
  title: 'Model & settings', model: 'Model', runtime: 'Runtime & GPU', tuning: 'Performance & memory', sampling: 'Generation', reasoning: 'Reasoning', adapters: 'Auxiliary models & LoRA', advanced: 'Advanced', profiles: 'Profiles',
  search: 'Search models', path: 'Model path', selected: 'Selected', empty: 'No matching models. Enter a model path or manage the model folder.', refresh: 'Refresh', browse: 'Choose file',
  draft: 'Options are edited in the selected profile. Save to keep your changes.', save: 'Save profile', saveTarget: 'Save to: {name}', start: 'Save profile & start', cancel: 'Cancel', close: 'Close',
  discardTitle: 'Discard unsaved changes?', discardBody: 'Your changes to the selected profile have not been saved.', discard: 'Discard changes', keep: 'Keep editing',
  pending: 'Saving…', benchmarkControlled: 'Context size, concurrency, timeout and sampling are determined by the benchmark workloads. Chat prompts and request settings are not used.',
  selectRuntime: 'Select a runtime', manageRuntime: 'Manage runtimes', missingRuntime: 'The selected runtime is not installed. You can save these settings, but install the runtime before starting.',
  reset: 'Reset to runtime defaults', preset: 'Load preset', balanced: 'Balanced', cpu: 'CPU', maxGpu: 'Max GPU', tuningProfile: 'Load model tuning profile',
  invalid: 'Correct invalid fields before applying.', rawArgs: 'Extra server arguments (one per line)', rawChat: 'Extra request JSON',
  projector: 'Vision projector', draftModel: 'Draft model', none: 'None', addLora: 'Add LoRA file', scale: 'Scale', enabled: 'Enabled', remove: 'Remove',
  shared: 'Shared profile management', sharedHint: 'Shared profiles have separate Save and Delete actions. Completed changes remain even if you cancel this model settings editor.',
  load: 'Load into editor', saveProfile: 'Save shared profile', newProfile: 'Save as new profile', deleteProfile: 'Delete shared profile', profileName: 'Profile name', serverProfile: 'Server profile', modelProfile: 'Generation profile', prompt: 'Default system prompt', stop: 'Stop strings (one per line)', profileSaved: 'Shared profile saved.', profileDeleted: 'Shared profile deleted.', profileDeleteConfirm: 'Delete this shared profile?',
  gpu: 'GPU placement', automatic: 'Automatic', tensorSplit: 'Tensor split (comma-separated weights)', truncated: 'The model list was truncated. Narrow the model folder or enter a path.', failureDetails: 'Details',
  optionsTruncated: 'Showing {shown} of {total} matching options. Narrow the search to see the rest.',
  options: 'Runtime options', optionSearch: 'Search runtime options', optionApply: 'Update editor', unavailable: 'Unavailable',
};
type Copy = { [K in keyof typeof en]: string };
const ko: Copy = {
  saveConfirmTitle: '이 변경을 “{name}” 프로필에 저장할까요?', saveConfirmUnchanged: '이 프로필에서 바뀌는 항목이 없습니다.',
  saveConfirmAction: '변경 저장',
  pasteLabel: 'llama-server 명령 붙여넣기', pasteHint: '모델 카드나 게시글의 명령을 붙여넣으면 아래 설정에 반영됩니다. 줄바꿈 기호와 따옴표 경로도 인식합니다.', pastePlaceholder: '-c 131072 -ngl 999 -fa on --temp 0.7', pasteApply: '붙여넣은 설정 적용', pasteApplied: '{count}개 설정을 적용했습니다.', pasteRejected: '적용하지 못한 항목:', pasteUnknown: '이 앱에 해당 설정이 없습니다', pasteMissing: '값이 없습니다', pasteBadValue: '허용 범위를 벗어났습니다',
  restart: '프로필 저장 후 다시 실행', switchStart: '프로필 저장 후 전환하여 실행',
  projectPromptHint: '시스템 프롬프트는 모델 설정에서 프로필에 저장합니다.',
  profileInUse: '실행 중인 모델이 이 프로필로 시작되었습니다. 설정을 바꾸려면 모델을 중지하거나 다른 프로필로 저장하세요.', profilePending: '프로필 작업을 마치거나 취소한 뒤 저장하세요.', pathPending: '입력한 모델 경로를 선택한 뒤 저장하세요.',
  title: '모델 선택·설정', model: '모델', runtime: '런타임·GPU', tuning: '성능·메모리', sampling: '생성', reasoning: '추론', adapters: '보조 모델·LoRA', advanced: '고급', profiles: '프로필',
  search: '모델 검색', path: '모델 경로', selected: '선택됨', empty: '일치하는 모델이 없습니다. 모델 경로를 입력하거나 모델 폴더를 관리하세요.', refresh: '새로고침', browse: '파일 선택',
  draft: '선택한 프로필의 옵션을 편집합니다. 변경을 유지하려면 저장하세요.', save: '프로필 저장', saveTarget: '저장 대상: {name}', start: '프로필 저장 후 실행', cancel: '취소', close: '닫기',
  discardTitle: '편집 중인 변경을 버릴까요?', discardBody: '선택한 프로필의 변경 사항이 아직 저장되지 않았습니다.', discard: '변경 버리기', keep: '계속 편집', pending: '저장 중…',
  benchmarkControlled: '컨텍스트 크기·동시 요청 수·시간 제한·샘플링은 벤치마크 측정 조건에서 결정합니다. 채팅 프롬프트와 요청 설정은 사용하지 않습니다.',
  selectRuntime: '런타임 선택', manageRuntime: '런타임 관리', missingRuntime: '선택한 런타임이 설치되지 않았습니다. 설정은 저장할 수 있지만 실행 전에 런타임을 설치해야 합니다.',
  reset: '런타임 기본값으로 초기화', preset: '프리셋 불러오기', balanced: '균형', cpu: 'CPU', maxGpu: '최대 GPU', tuningProfile: '모델 튜닝 프로필 불러오기',
  invalid: '잘못 입력된 항목을 수정한 뒤 적용하세요.', rawArgs: '추가 서버 인자 (한 줄에 하나)', rawChat: '추가 요청 JSON',
  projector: '비전 프로젝터', draftModel: '초안 모델', none: '없음', addLora: 'LoRA 파일 추가', scale: '배율', enabled: '사용', remove: '제거',
  shared: '공유 프로필 관리', sharedHint: '공유 프로필은 별도의 저장·삭제 버튼으로 반영합니다. 완료한 변경은 모델 설정 편집기를 취소해도 유지됩니다.',
  load: '편집기에 불러오기', saveProfile: '공유 프로필 저장', newProfile: '새 프로필로 저장', deleteProfile: '공유 프로필 삭제', profileName: '프로필 이름', serverProfile: '서버 프로필', modelProfile: '생성 프로필', prompt: '기본 시스템 프롬프트', stop: '중지 문자열 (한 줄에 하나)', profileSaved: '공유 프로필을 저장했습니다.', profileDeleted: '공유 프로필을 삭제했습니다.', profileDeleteConfirm: '이 공유 프로필을 삭제할까요?',
  gpu: 'GPU 배치', automatic: '자동', tensorSplit: '텐서 분할 (쉼표로 구분한 비중)', truncated: '모델 목록이 일부만 표시됩니다. 모델 폴더 범위를 줄이거나 경로를 입력하세요.', failureDetails: '자세히',
  optionsTruncated: '일치하는 {total}개 중 {shown}개를 표시합니다. 검색으로 좁히면 나머지를 볼 수 있습니다.',
  options: '런타임 옵션', optionSearch: '런타임 옵션 검색', optionApply: '편집기에 반영', unavailable: '사용 불가',
};
const ja: Copy = {
  saveConfirmTitle: 'この変更を「{name}」に保存しますか？', saveConfirmUnchanged: 'このプロファイルで変わる項目はありません。',
  pasteLabel: 'llama-server コマンドを貼り付け', pasteHint: 'モデルカードや投稿のコマンドを貼り付けると、下の設定に反映されます。行継続と引用符付きパスも解釈します。', pastePlaceholder: '-c 131072 -ngl 999 -fa on --temp 0.7', pasteApply: '貼り付けた設定を適用', pasteApplied: '{count}件の設定を適用しました。', pasteRejected: '適用できなかった項目:', pasteUnknown: 'このアプリに対応する設定がありません', pasteMissing: '値がありません', pasteBadValue: '許容範囲外です',
  saveConfirmAction: '変更を保存',
  restart: 'プロファイルを保存して再起動', switchStart: 'プロファイルを保存して切り替え・起動',
  projectPromptHint: 'このプロンプトはモデル設定で編集し、プロファイルに保存してください。',
  profileInUse: '実行中のモデルはこのプロファイルで起動されています。設定を変更するにはモデルを停止するか、別のプロファイルに保存してください。', profilePending: 'プロファイルの操作を完了またはキャンセルしてから保存してください。', pathPending: '入力したモデルパスを選択してから保存してください。',
  title: 'モデル選択・設定', model: 'モデル', runtime: 'ランタイム・GPU', tuning: '性能・メモリ', sampling: '生成', reasoning: '推論', adapters: '補助モデル・LoRA', advanced: '詳細', profiles: 'プロファイル',
  search: 'モデルを検索', path: 'モデルパス', selected: '選択中', empty: '一致するモデルがありません。パスを入力するかモデルフォルダーを管理してください。', refresh: '更新', browse: 'ファイルを選択',
  draft: '選択中のプロファイルの設定を編集します。変更を保持するには保存してください。', save: 'プロファイルを保存', saveTarget: '保存先: {name}', start: 'プロファイルを保存して起動', cancel: 'キャンセル', close: '閉じる',
  discardTitle: '未保存の変更を破棄しますか？', discardBody: '選択中のプロファイルの変更はまだ保存されていません。', discard: '変更を破棄', keep: '編集を続ける', pending: '保存中…',
  benchmarkControlled: 'コンテキスト、同時リクエスト数、タイムアウト、サンプリングは測定条件で決まります。チャットのプロンプトとリクエスト設定は使用しません。',
  selectRuntime: 'ランタイムを選択', manageRuntime: 'ランタイム管理', missingRuntime: '選択したランタイムは未インストールです。設定は保存できますが起動前にインストールしてください。',
  reset: 'ランタイム既定値に戻す', preset: 'プリセットを読み込む', balanced: 'バランス', cpu: 'CPU', maxGpu: '最大 GPU', tuningProfile: 'モデルの調整プロファイルを読み込む',
  invalid: '無効な項目を修正してから適用してください。', rawArgs: '追加サーバー引数（1行に1つ）', rawChat: '追加リクエスト JSON',
  projector: '画像プロジェクター', draftModel: 'ドラフトモデル', none: 'なし', addLora: 'LoRA ファイルを追加', scale: '倍率', enabled: '有効', remove: '削除',
  shared: '共有プロファイル管理', sharedHint: '共有プロファイルは専用の保存・削除操作で反映します。完了した変更はモデル設定をキャンセルしても保持されます。',
  load: 'エディターに読み込む', saveProfile: '共有プロファイルを保存', newProfile: '新規プロファイルとして保存', deleteProfile: '共有プロファイルを削除', profileName: 'プロファイル名', serverProfile: 'サーバープロファイル', modelProfile: '生成プロファイル', prompt: '既定のシステムプロンプト', stop: '停止文字列（1行に1つ）', profileSaved: '共有プロファイルを保存しました。', profileDeleted: '共有プロファイルを削除しました。', profileDeleteConfirm: 'この共有プロファイルを削除しますか？',
  optionsTruncated: '一致する{total}件のうち{shown}件を表示しています。検索で絞り込むと残りを確認できます。',
  gpu: 'GPU 配置', automatic: '自動', tensorSplit: 'テンソル分割（カンマ区切りの重み）', truncated: 'モデル一覧が省略されています。フォルダーを絞るかパスを入力してください。', failureDetails: '詳細', options: 'ランタイムオプション', optionSearch: 'オプションを検索', optionApply: 'エディターを更新', unavailable: '利用不可',
};
const zh: Copy = {
  saveConfirmTitle: '将这些更改保存到“{name}”吗？', saveConfirmUnchanged: '此配置档没有任何项目会改变。',
  pasteLabel: '粘贴 llama-server 命令', pasteHint: '粘贴模型卡片或帖子中的命令，其参数会填入下方设置。支持换行续行符和带引号的路径。', pastePlaceholder: '-c 131072 -ngl 999 -fa on --temp 0.7', pasteApply: '应用粘贴的设置', pasteApplied: '已应用 {count} 项设置。', pasteRejected: '未应用的项目：', pasteUnknown: '本应用没有对应的设置', pasteMissing: '缺少值', pasteBadValue: '超出允许范围',
  restart: '保存预设并重启', switchStart: '保存预设、切换并启动',
  saveConfirmAction: '保存更改',
  projectPromptHint: '请在模型设置中编辑此提示词并保存到预设。',
  profileInUse: '正在运行的模型由该配置档启动。要更改这些设置，请先停止模型或保存到其他配置档。', profilePending: '请先完成或取消预设操作，再保存。', pathPending: '请先选择输入的模型路径，再保存。',
  title: '模型选择与设置', model: '模型', runtime: '运行时与 GPU', tuning: '性能与内存', sampling: '生成', reasoning: '推理', adapters: '辅助模型与 LoRA', advanced: '高级', profiles: '配置预设',
  search: '搜索模型', path: '模型路径', selected: '已选择', empty: '没有匹配的模型。请输入路径或管理模型目录。', refresh: '刷新', browse: '选择文件',
  draft: '正在编辑所选预设中的选项。保存即可保留更改。', save: '保存预设', saveTarget: '保存到: {name}', start: '保存预设并启动', cancel: '取消', close: '关闭',
  discardTitle: '放弃未保存的修改？', discardBody: '所选预设的更改尚未保存。', discard: '放弃修改', keep: '继续编辑', pending: '正在保存…',
  benchmarkControlled: '上下文大小、并发请求数、超时和采样由测试条件决定。不使用聊天提示词和请求设置。',
  selectRuntime: '选择运行时', manageRuntime: '管理运行时', missingRuntime: '所选运行时尚未安装。可以保存设置，但启动前需要安装运行时。',
  reset: '恢复运行时默认值', preset: '加载预设', balanced: '均衡', cpu: 'CPU', maxGpu: '最大 GPU', tuningProfile: '加载模型调优预设',
  invalid: '请修正无效项目后再应用。', rawArgs: '附加服务器参数（每行一个）', rawChat: '附加请求 JSON',
  projector: '视觉投影器', draftModel: '草稿模型', none: '无', addLora: '添加 LoRA 文件', scale: '倍率', enabled: '启用', remove: '移除',
  shared: '共享预设管理', sharedHint: '共享预设通过单独的保存和删除操作生效。即使取消模型设置编辑器，已完成的修改也会保留。',
  load: '加载到编辑器', saveProfile: '保存共享预设', newProfile: '另存为新预设', deleteProfile: '删除共享预设', profileName: '预设名称', serverProfile: '服务器预设', modelProfile: '生成预设', prompt: '默认系统提示词', stop: '停止字符串（每行一个）', profileSaved: '已保存共享预设。', profileDeleted: '已删除共享预设。', profileDeleteConfirm: '删除此共享预设？',
  optionsTruncated: '在匹配的 {total} 项中显示 {shown} 项。请缩小搜索范围以查看其余项。',
  gpu: 'GPU 分配', automatic: '自动', tensorSplit: '张量分割（逗号分隔权重）', truncated: '模型列表已截断。请缩小模型目录范围或输入路径。', failureDetails: '详情', options: '运行时选项', optionSearch: '搜索运行时选项', optionApply: '更新编辑器', unavailable: '不可用',
};
export const modelSettingsCopy = { en, ko, ja, zh };
export type ModelSettingsCopy = Copy;
