const en = {
  profiles: 'Settings profiles', editingTitle: '{name} · Editing', editing: 'Editing',
  unsaved: 'Unsaved changes',
  namedHint: '{scope} profile · selected for this model', editingHint: '{scope} profile · unsaved changes',
  preset: 'Preset', global: 'Global', model: 'Model', presetProfiles: 'Preset profiles', globalProfiles: 'Global profiles', modelProfiles: 'Model profiles',
  emptyPreset: 'No presets for this model', emptyGlobal: 'No global profiles', emptyModel: 'No profiles for this model',
  preview: 'Preview', previewHint: 'Saved values. Select this profile to use it for this model.', closePreview: 'Close preview',
  current: 'Current values', active: 'Selected', readonly: 'Read only',
  apply: 'Select this profile', saveAs: 'Save as new', create: 'Create new profile',
  rename: 'Rename', remove: 'Delete profile', revert: 'Revert',
  name: 'Profile name', scope: 'Scope', cancel: 'Cancel', done: 'Save name',
  deleteConfirm: 'Delete “{name}”?', deleteHint: 'Models using this profile will switch to the default profile, “{name}”.',
  defaultProfile: 'Default profile', setDefault: 'Set as default',
  defaultDeleteHint: 'The default profile cannot be deleted. Set another profile as the default first.',
  modelDefaultHint: 'Setting this profile as default makes it available to all models.',
  defaults: 'Defaults', defaultsSummary: 'Default values used when an option has no override.',
  resetAll: 'Reset all to defaults', resetDone: 'Reset to defaults.', resetUnchanged: 'Already using defaults.',
  pendingChanges: 'This save changes {count} settings:', changeTo: 'to',
  runtimeDefault: 'Runtime default', empty: 'None', on: 'On', off: 'Off', prompt: 'System prompt',
  sampling: 'Sampling', capacity: 'Capacity and performance', reasoning: 'Reasoning', runtime: 'Runtime and model', advanced: 'Additional settings',
  error: 'The profile could not be saved. Try again.', saveGlobalHint: 'Selecting this profile for another model uses all its saved settings.',
};
type Copy = typeof en;
const ko: Copy = {
  profiles: '설정 프로필', editingTitle: '{name} · 편집 중', editing: '편집 중',
  unsaved: '저장하지 않은 변경',
  namedHint: '{scope} 프로필 · 이 모델에서 사용 중', editingHint: '{scope} 프로필 · 저장하지 않은 변경',
  preset: '프리셋', global: '공용', model: '모델', presetProfiles: '프리셋 프로필', globalProfiles: '공용 프로필', modelProfiles: '모델 프로필',
  emptyPreset: '이 모델에 맞는 프리셋이 없습니다', emptyGlobal: '공용 프로필이 없습니다', emptyModel: '이 모델의 프로필이 없습니다',
  preview: '미리보기', previewHint: '저장된 값입니다. 이 모델에 사용하려면 이 프로필을 선택하세요.', closePreview: '미리보기 닫기',
  current: '현재 설정', active: '사용 중', readonly: '읽기 전용',
  apply: '이 프로필 선택', saveAs: '새 프로필로 저장', create: '새 프로필 생성',
  rename: '이름 변경', remove: '프로필 삭제', revert: '저장된 설정으로 복원',
  name: '프로필 이름', scope: '사용 범위', cancel: '취소', done: '이름 저장',
  deleteConfirm: '“{name}” 프로필을 삭제할까요?', deleteHint: '이 프로필을 사용하는 모델은 기본 프로필인 “{name}” 프로필로 전환됩니다.',
  defaultProfile: '기본 프로필', setDefault: '기본 프로필로 지정',
  defaultDeleteHint: '기본 프로필은 삭제할 수 없습니다. 먼저 다른 프로필을 기본으로 지정하세요.',
  modelDefaultHint: '기본 프로필로 지정하면 모든 모델에서 사용할 수 있습니다.',
  defaults: '기본값', defaultsSummary: '옵션에 별도 값을 지정하지 않았을 때 사용하는 기본값입니다.',
  resetAll: '전체 기본값으로 초기화', resetDone: '기본값으로 초기화했습니다.', resetUnchanged: '이미 기본값입니다.',
  pendingChanges: '이 저장으로 {count}개 설정이 바뀝니다:', changeTo: '→',
  runtimeDefault: '런타임 기본값', empty: '없음', on: '켜짐', off: '꺼짐', prompt: '시스템 프롬프트',
  sampling: '샘플링', capacity: '용량 및 성능', reasoning: '추론', runtime: '런타임 및 모델', advanced: '추가 설정',
  error: '프로필을 저장하지 못했습니다. 다시 시도하세요.', saveGlobalHint: '다른 모델에서 이 프로필을 선택하면 저장된 모든 설정을 사용합니다.',
};
const ja: Copy = {
  profiles: '設定プロファイル', editingTitle: '{name} · 編集中', editing: '編集中',
  unsaved: '未保存の変更',
  namedHint: '{scope}プロファイル · このモデルで使用中', editingHint: '{scope}プロファイル · 未保存の変更',
  preset: 'プリセット', global: '共通', model: 'モデル', presetProfiles: 'プリセット', globalProfiles: '共通プロファイル', modelProfiles: 'モデルプロファイル',
  emptyPreset: 'このモデルのプリセットはありません', emptyGlobal: '共通プロファイルはありません', emptyModel: 'このモデルのプロファイルはありません',
  preview: 'プレビュー', previewHint: '保存済みの設定です。このモデルで使うには、このプロファイルを選択してください。', closePreview: 'プレビューを閉じる',
  current: '現在の設定値', active: '使用中', readonly: '読み取り専用',
  apply: 'このプロファイルを選択', saveAs: '新規として保存', create: '新しいプロファイルを作成',
  rename: '名前を変更', remove: 'プロファイルを削除', revert: '元に戻す',
  name: 'プロファイル名', scope: '範囲', cancel: 'キャンセル', done: '名前を保存',
  deleteConfirm: '「{name}」を削除しますか？', deleteHint: 'このプロファイルを使用するモデルは、既定のプロファイル「{name}」に切り替わります。',
  defaultProfile: '既定のプロファイル', setDefault: '既定に設定',
  defaultDeleteHint: '既定のプロファイルは削除できません。先に別のプロファイルを既定に設定してください。',
  modelDefaultHint: '既定に設定すると、すべてのモデルで使用できるようになります。',
  defaults: '既定値', defaultsSummary: '個別の値を指定していない場合に使用する既定値です。',
  resetAll: 'すべて既定値に戻す', resetDone: '既定値に戻しました。', resetUnchanged: 'すでに既定値です。',
  pendingChanges: 'この保存で{count}件の設定が変わります:', changeTo: '→',
  runtimeDefault: 'ランタイムの既定値', empty: 'なし', on: 'オン', off: 'オフ', prompt: 'システムプロンプト',
  sampling: 'サンプリング', capacity: '容量とパフォーマンス', reasoning: '推論', runtime: 'ランタイムとモデル', advanced: '追加設定',
  error: 'プロファイルを保存できませんでした。再試行してください。', saveGlobalHint: '別のモデルでこのプロファイルを選択すると、保存済みのすべての設定を使用します。',
};
const zh: Copy = {
  profiles: '设置预设', editingTitle: '{name} · 编辑中', editing: '编辑中',
  unsaved: '未保存的更改',
  namedHint: '{scope}预设 · 此模型正在使用', editingHint: '{scope}预设 · 未保存的更改',
  preset: '内置', global: '通用', model: '模型', presetProfiles: '内置预设', globalProfiles: '通用预设', modelProfiles: '模型预设',
  emptyPreset: '此模型没有内置预设', emptyGlobal: '没有通用预设', emptyModel: '此模型没有预设',
  preview: '预览', previewHint: '这些是已保存的值。选择此预设后用于此模型。', closePreview: '关闭预览',
  current: '当前设置', active: '使用中', readonly: '只读',
  apply: '选择此预设', saveAs: '另存为新预设', create: '创建新预设',
  rename: '重命名', remove: '删除预设', revert: '恢复原值',
  name: '预设名称', scope: '范围', cancel: '取消', done: '保存名称',
  deleteConfirm: '删除“{name}”？', deleteHint: '使用此预设的模型将切换到默认预设“{name}”。',
  defaultProfile: '默认预设', setDefault: '设为默认',
  defaultDeleteHint: '无法删除默认预设。请先将其他预设设为默认。',
  modelDefaultHint: '设为默认后，此预设可供所有模型使用。',
  defaults: '默认值', defaultsSummary: '未单独指定选项值时使用的默认值。',
  resetAll: '全部重置为默认值', resetDone: '已重置为默认值。', resetUnchanged: '已在使用默认值。',
  pendingChanges: '本次保存将更改 {count} 项设置：', changeTo: '→',
  runtimeDefault: '运行时默认值', empty: '无', on: '开', off: '关', prompt: '系统提示词',
  sampling: '采样', capacity: '容量和性能', reasoning: '推理', runtime: '运行时和模型', advanced: '其他设置',
  error: '无法保存预设。请重试。', saveGlobalHint: '为其他模型选择此预设时，会使用其中保存的全部设置。',
};

export const profileControlCopy = { en, ko, ja, zh };

const fieldLabels: Record<string, [string, string, string, string]> = {
  temperature: ['Temperature', '온도', '温度', '温度'], top_p: ['Top P', 'Top P', 'Top P', 'Top P'], top_k: ['Top K', 'Top K', 'Top K', 'Top K'],
  min_p: ['Min P', 'Min P', 'Min P', 'Min P'], max_tokens: ['Maximum output tokens', '최대 출력 토큰', '最大出力トークン', '最大输出令牌'],
  stop: ['Stop sequences', '중지 문자열', '停止文字列', '停止字符串'], seed: ['Seed', '시드', 'シード', '随机种子'],
  ctx_size: ['Context size', '컨텍스트 크기', 'コンテキスト長', '上下文长度'], batch_size: ['Batch size', '배치 크기', 'バッチサイズ', '批次大小'],
  ubatch_size: ['Physical batch size', '물리 배치 크기', '物理バッチサイズ', '物理批次大小'], keep: ['Tokens to keep', '유지할 토큰', '保持トークン数', '保留令牌'],
  threads: ['CPU threads', 'CPU 스레드', 'CPU スレッド', 'CPU 线程'], parallel: ['Parallel requests', '병렬 요청', '並列リクエスト', '并行请求'],
  request_timeout_seconds: ['Request timeout (s)', '요청 제한 시간(초)', 'リクエスト期限（秒）', '请求超时（秒）'], sleep_idle_seconds: ['Idle timeout (s)', '유휴 시간(초)', 'アイドル期限（秒）', '空闲超时（秒）'],
  cache_type_k: ['Key cache type', '키 캐시 형식', 'キーキャッシュ形式', '键缓存类型'], cache_type_v: ['Value cache type', '값 캐시 형식', '値キャッシュ形式', '值缓存类型'],
  flash_attn: ['Flash attention', '플래시 어텐션', 'Flash Attention', 'Flash Attention'], ngl: ['GPU layers', 'GPU 레이어', 'GPU レイヤー', 'GPU 层'],
  n_cpu_moe: ['CPU expert layers', 'CPU 전문가 레이어', 'CPU エキスパート層', 'CPU 专家层'],
  active_backend: ['Runtime', '런타임', 'ランタイム', '运行时'], active_build: ['Runtime build', '런타임 빌드', 'ランタイムビルド', '运行时版本'],
  gpu: ['GPU placement', 'GPU 배치', 'GPU 配置', 'GPU 分配'], mmproj: ['Vision projector', '비전 프로젝터', '画像プロジェクター', '视觉投影器'],
  lora_adapters: ['LoRA adapters', 'LoRA 어댑터', 'LoRA アダプター', 'LoRA 适配器'], server_args: ['Additional runtime arguments', '추가 런타임 인수', '追加ランタイム引数', '其他运行时参数'],
  reasoning: ['Reasoning', '추론', '推論', '推理'], reasoning_format: ['Reasoning format', '추론 형식', '推論形式', '推理格式'],
  reasoning_effort: ['Reasoning effort', '추론 강도', '推論の強度', '推理强度'], reasoning_budget: ['Reasoning budget', '추론 예산', '推論予算', '推理预算'],
  reasoning_budget_message: ['Reasoning limit message', '추론 제한 메시지', '推論制限メッセージ', '推理限制消息'], reasoning_preserve: ['Preserve reasoning', '추론 보존', '推論を保持', '保留推理'],
  spec_type: ['Speculative decoding', '추측 디코딩', '投機的デコード', '推测解码'], spec_draft_model: ['Draft model', '드래프트 모델', 'ドラフトモデル', '草稿模型'],
  spec_draft_n_max: ['Maximum draft tokens', '최대 드래프트 토큰', '最大ドラフトトークン', '最大草稿令牌'], spec_draft_n_min: ['Minimum draft tokens', '최소 드래프트 토큰', '最小ドラフトトークン', '最小草稿令牌'],
  spec_draft_p_min: ['Draft acceptance threshold', '드래프트 수락 임계값', 'ドラフト採用しきい値', '草稿接受阈值'], spec_draft_p_split: ['Draft split threshold', '드래프트 분할 임계값', 'ドラフト分岐しきい値', '草稿拆分阈值'],
  spec_draft_ngl: ['Draft GPU layers', '드래프트 GPU 레이어', 'ドラフト GPU レイヤー', '草稿 GPU 层'], spec_draft_device: ['Draft device', '드래프트 장치', 'ドラフトデバイス', '草稿设备'],
};
export function profileFieldLabel(key: string, locale: keyof typeof profileControlCopy): string {
  return fieldLabels[key]?.[({ en: 0, ko: 1, ja: 2, zh: 3 })[locale]]
    ?? key.replace(/_/g, ' ').replace(/^./, letter => letter.toUpperCase());
}
