import type { Locale } from '../../shared/i18n/i18n';

const en = {
  title: 'Before loading', estimated: 'Estimated memory · updates with settings',
  ramTotal: 'Total RAM', totalMemory: 'VRAM + RAM',
  workingSetHint: 'Selected model only · excludes other apps and OS file cache',
  fileCacheHint: 'Total RAM includes Runtime RAM and RAM Offload. Reading model files can also populate reclaimable OS file cache, including while uploading weights to the GPU. This cache is not a fixed allocation and is excluded from these estimates. System monitors may include it or memory used by other apps; compare usage before and after loading with the same other workloads.',
  vram: 'VRAM', ramOffload: 'RAM Offload', ssdOffload: 'SSD Offload',
  select: 'Select a model and runtime to estimate resources.', invalid: 'Finish editing valid settings to update the estimate.',
  loading: 'Calculating…', unknown: 'Unavailable', error: 'Could not estimate resources.', retry: 'Retry estimate',
  details: 'Estimate details', requiredVram: 'Requested VRAM', vramCapacity: 'Total VRAM', capacity: 'Total system memory',
  hostMemory: 'Runtime RAM', hostMemoryHelp: 'About runtime RAM',
  hostMemoryHint: 'System memory needed even for GPU execution. Includes input embeddings, working buffers and runtime overhead.',
  ramTotalHint: 'Total RAM = Runtime RAM + RAM Offload.', kv: 'KV cache',
  storedFiles: 'Stored model files', modelFiles: 'Main model files', auxiliaryFiles: 'Projector, draft & adapter files', incomplete: 'Partial file size',
  exceedsMemory: 'Exceeds VRAM and RAM capacity', exceedsVram: 'Requested VRAM exceeds capacity',
   scope: 'VRAM, Runtime RAM, RAM Offload and SSD Offload are estimated values for this configuration, not measurements. RAM Offload is model/cache data placed in system memory after VRAM and excludes Runtime RAM. SSD Offload is the estimated model/cache portion read from disk for this configuration — weights explicitly placed on disk plus any overflow beyond VRAM and RAM capacity — not the installation size.',
  capacityHint: 'Capacity is the total physical memory of this computer. Memory used by other apps and running models is not subtracted, so less may be free when loading.',
  filesHint: 'Stored model files are the selected files already on disk, including all shards; they are not SSD Offload. Loading does not copy them, and context or batch changes do not change their size.',
  benchmark: 'Benchmark runs override some settings; each run can use a different amount of memory.',
  notes: {
    approximate: 'Calculated from GGUF metadata with estimated working buffers, not measured. Runtime versions, drivers, memory mapping and workload can change actual and peak usage.',
    automatic: 'Automatic runtime settings are estimated with the runtime\'s baseline defaults, not the most extreme placement. Set explicit values for a more specific estimate.',
    missing_metadata: 'The model does not provide enough readable GGUF metadata to estimate memory.',
    unsupported_architecture: 'This model architecture needs a runtime measurement for a reliable memory estimate.',
    missing_files: 'Some selected files or shards are missing or unreadable. The stored file total is incomplete.',
    auxiliary: 'Includes memory for the projector, draft model or adapters; their working memory depends on the workload.',
    shared_memory: 'The selected backend may share system memory. VRAM and RAM Offload are not necessarily separate physical pools.',
    advanced_options: 'Advanced memory or placement options prevent a reliable estimate for this configuration.',
    capacity_unknown: 'Total VRAM or system memory could not be detected, so the split between VRAM, RAM Offload and SSD Offload is uncertain.',
    placement_adjustment: 'The requested GPU placement needs more VRAM than the device has. The excess is shown as the RAM or SSD Offload this configuration would require; the runtime does not move it automatically. Adjust GPU layers or offload settings before loading.',
     disk_offload: 'The part that does not fit in VRAM and RAM can only be read through disk-backed access, such as memory-mapped files, when the runtime and settings allow it. Expect much slower generation or a failed load.',
    lazy_offload: 'Eligible embedding weights are read on demand under the configured lazy mode: on reads them from disk, auto does so when they exceed 4 GiB, and off keeps them in memory.',
  },
};
type Copy = Omit<typeof en, 'notes'> & { notes: Record<keyof typeof en.notes, string> };
export const resourceEstimateCopy: Record<Locale, Copy> = {
  en,
  ko: {
    title: '실행 전 예상 사용량', estimated: '메모리 추정 · 설정 변경 시 갱신',
    ramTotal: 'RAM 합계', totalMemory: 'VRAM + RAM',
    workingSetHint: '선택한 모델 기준 · 다른 앱·OS 파일 캐시 제외',
    fileCacheHint: 'RAM 합계는 실행 보조 RAM과 RAM 오프로드를 합한 값입니다. 모델 파일을 읽거나 GPU로 올릴 때 회수 가능한 OS 파일 캐시가 RAM에 남을 수 있습니다. 이 캐시는 고정 할당량이 아니므로 예상치에서 제외합니다. 시스템 모니터에는 캐시나 다른 앱의 메모리가 함께 표시될 수 있으므로, 다른 작업을 동일하게 유지한 채 모델 실행 전후의 증가량을 비교하세요.',
    vram: 'VRAM', ramOffload: 'RAM 오프로드', ssdOffload: 'SSD 오프로드',
    select: '모델과 런타임을 선택하면 사용량을 계산합니다.', invalid: '설정 입력을 올바르게 마치면 예상 사용량이 갱신됩니다.',
    loading: '계산 중…', unknown: '계산 불가', error: '사용량을 계산하지 못했습니다.', retry: '예상 사용량 다시 계산',
    details: '계산 상세', requiredVram: '요청된 VRAM', vramCapacity: '전체 VRAM', capacity: '전체 시스템 메모리',
    hostMemory: '실행 보조 RAM', hostMemoryHelp: '실행 보조 RAM 설명',
    hostMemoryHint: 'GPU 실행에도 필요한 시스템 메모리입니다. 입력 임베딩·작업 버퍼·런타임 비용을 포함합니다.',
    ramTotalHint: 'RAM 합계 = 실행 보조 RAM + RAM 오프로드.', kv: 'KV 캐시',
    storedFiles: '저장된 모델 파일', modelFiles: '주 모델 파일', auxiliaryFiles: '프로젝터·드래프트·어댑터 파일', incomplete: '일부 파일 크기',
    exceedsMemory: 'VRAM과 RAM 용량 초과', exceedsVram: '요청 VRAM이 용량 초과',
     scope: 'VRAM, 실행 보조 RAM, RAM 오프로드, SSD 오프로드는 이 설정의 추정치이며 실측값이 아닙니다. RAM 오프로드는 VRAM 다음으로 시스템 메모리에 두는 모델/캐시 데이터로, 실행 보조 RAM은 제외합니다. SSD 오프로드는 이 설정에서 디스크에서 읽는 모델/캐시 예상 분량 — 명시적으로 디스크에 배치한 가중치와 VRAM·RAM 용량을 초과한 분량 — 이며 설치 크기가 아닙니다.',
    capacityHint: '용량은 이 컴퓨터의 전체 물리 메모리 기준입니다. 다른 앱과 실행 중인 모델이 사용하는 메모리는 빼지 않았으므로 실행 시 여유 메모리는 더 적을 수 있습니다.',
    filesHint: '저장된 모델 파일은 분할 파일을 포함해 선택한 파일이 이미 디스크에서 차지하는 크기이며 SSD 오프로드가 아닙니다. 실행 시 복사되지 않고, 컨텍스트·배치 변경으로 크기가 바뀌지 않습니다.',
    benchmark: '벤치마크는 일부 설정을 덮어쓰므로 각 실행의 메모리 사용량이 달라질 수 있습니다.',
    notes: {
      approximate: 'GGUF 메타데이터와 작업 버퍼 추정치로 계산한 값이며 실측이 아닙니다. 런타임 버전·드라이버·메모리 매핑·작업에 따라 실제 사용량과 최대 사용량은 달라질 수 있습니다.',
      automatic: '자동으로 정해지는 런타임 설정은 극단적인 배치가 아니라 런타임 기본 동작을 기준으로 계산했습니다. 값을 직접 지정하면 더 구체적으로 추정할 수 있습니다.',
      missing_metadata: '메모리를 계산할 수 있는 GGUF 메타데이터가 부족하거나 읽을 수 없습니다.',
      unsupported_architecture: '이 모델 구조의 메모리는 런타임 실측이 필요합니다.',
      missing_files: '일부 파일이나 분할 파일이 없거나 읽을 수 없어 저장된 파일 합계가 불완전합니다.',
      auxiliary: '프로젝터·드래프트 모델·어댑터의 메모리를 포함하며, 이들의 작업 메모리는 작업에 따라 달라집니다.',
      shared_memory: '선택한 백엔드는 시스템 메모리를 공유할 수 있습니다. VRAM과 RAM 오프로드가 별도의 물리 메모리는 아닐 수 있습니다.',
      advanced_options: '고급 메모리·배치 옵션으로 인해 이 설정의 사용량을 신뢰성 있게 계산할 수 없습니다.',
      capacity_unknown: '전체 VRAM 또는 시스템 메모리 용량을 확인하지 못해 VRAM, RAM 오프로드, SSD 오프로드 사이의 배분이 불확실합니다.',
      placement_adjustment: '요청한 GPU 배치에 필요한 VRAM이 장치 용량보다 큽니다. 초과분은 이 설정에 필요한 RAM·SSD 오프로드로 표시했으며, 런타임이 자동으로 옮겨 주지 않습니다. 실행 전에 GPU 레이어 수나 오프로드 설정을 조정하세요.',
       disk_offload: 'VRAM과 RAM에 들어가지 않는 부분은 런타임과 설정이 허용할 때만 메모리 매핑 같은 디스크 기반 접근으로 읽을 수 있습니다. 생성이 크게 느려지거나 로드에 실패할 수 있습니다.',
      lazy_offload: '대상 임베딩 가중치는 lazy-mode 설정에 따라 필요할 때 디스크에서 읽습니다. on은 디스크에서 읽고, auto는 4 GiB를 초과할 때 디스크에서 읽으며, off는 메모리에 유지합니다.',
    },
  },
  ja: {
    title: '読み込み前の使用量', estimated: 'メモリの推定値 · 設定変更で更新',
    ramTotal: 'RAM 合計', totalMemory: 'VRAM + RAM',
    workingSetHint: '選択したモデルのみ · 他のアプリと OS ファイルキャッシュを除外',
    fileCacheHint: 'RAM 合計は実行補助 RAM と RAM オフロードの合計です。モデルファイルの読み込みや GPU への転送時には、回収可能な OS ファイルキャッシュが RAM に残る場合があります。このキャッシュは固定割り当てではないため推定値に含みません。システムモニターにはキャッシュや他のアプリのメモリも含まれる場合があるため、他の処理を同じ状態に保ち、読み込み前後の増加量を比較してください。',
    vram: 'VRAM', ramOffload: 'RAM オフロード', ssdOffload: 'SSD オフロード',
    select: 'モデルとランタイムを選択すると使用量を推定します。', invalid: '設定の入力を正しく完了すると推定値が更新されます。',
    loading: '計算中…', unknown: '推定不可', error: '使用量を推定できませんでした。', retry: '使用量を再計算',
    details: '推定の詳細', requiredVram: '要求 VRAM', vramCapacity: 'VRAM 合計', capacity: 'システムメモリ合計',
    hostMemory: '実行補助 RAM', hostMemoryHelp: '実行補助 RAM の説明',
    hostMemoryHint: 'GPU 実行にも必要なシステムメモリです。入力埋め込み、作業バッファ、ランタイムの使用量を含みます。',
    ramTotalHint: 'RAM 合計 = 実行補助 RAM + RAM オフロード。', kv: 'KV キャッシュ',
    storedFiles: '保存済みモデルファイル', modelFiles: 'メインモデルファイル', auxiliaryFiles: 'プロジェクター・ドラフト・アダプターのファイル', incomplete: '一部ファイルのサイズ',
    exceedsMemory: 'VRAM と RAM の容量を超過', exceedsVram: '要求 VRAM が容量を超過',
     scope: 'VRAM、実行補助 RAM、RAM オフロード、SSD オフロードはこの設定の推定値で、実測値ではありません。RAM オフロードは VRAM の次にシステムメモリへ置くモデル/キャッシュデータで、実行補助 RAM は含みません。SSD オフロードはこの設定でディスクから読み出すモデル/キャッシュの推定量 — 明示的にディスク配置した重みと VRAM・RAM 容量を超えた分 — で、インストールサイズではありません。',
    capacityHint: '容量はこのコンピューターの物理メモリ合計です。他のアプリや実行中のモデルが使うメモリは差し引いていないため、読み込み時の空きはより少ない場合があります。',
    filesHint: '保存済みモデルファイルは分割ファイルを含む選択済みファイルのディスク上のサイズで、SSD オフロードではありません。読み込み時に複製されず、コンテキストやバッチの変更でもサイズは変わりません。',
    benchmark: 'ベンチマークでは一部の設定が上書きされるため、実行ごとに使用量が変わる場合があります。',
    notes: {
      approximate: 'GGUF メタデータと作業バッファの推定から算出した値で、実測ではありません。ランタイム、ドライバー、メモリマッピング、処理内容により実使用量とピークは異なります。',
      automatic: '自動で決まるランタイム設定は、極端な配置ではなくランタイムの既定動作を基準に推定しています。値を指定するとより具体的に推定できます。',
      missing_metadata: 'メモリ推定に必要な GGUF メタデータが不足しているか、読み取れません。',
      unsupported_architecture: 'このモデル構造にはランタイムでの実測が必要です。',
      missing_files: '一部のファイルが存在しないか読み取れないため、保存済みファイルの合計は不完全です。',
      auxiliary: 'プロジェクター、ドラフトモデル、アダプターのメモリを含みます。これらの作業メモリは処理内容により変わります。',
      shared_memory: '選択したバックエンドはシステムメモリを共有する場合があります。VRAM と RAM オフロードが別の物理メモリとは限りません。',
      advanced_options: '高度なメモリ・配置オプションにより、信頼できる推定ができません。',
      capacity_unknown: 'VRAM またはシステムメモリの合計を取得できなかったため、VRAM・RAM オフロード・SSD オフロードの配分は不確かです。',
      placement_adjustment: '要求された GPU 配置にはデバイスの容量を超える VRAM が必要です。超過分はこの設定に必要な RAM・SSD オフロードとして表示しており、ランタイムが自動で移すわけではありません。読み込み前に GPU レイヤー数やオフロード設定を調整してください。',
       disk_offload: 'VRAM と RAM に収まらない部分は、ランタイムと設定が許す場合に限り、メモリマップなどのディスク経由で読み込まれます。生成が大幅に遅くなるか、読み込みに失敗する可能性があります。',
      lazy_offload: '対象の埋め込み重みは lazy-mode の設定に従い必要時にディスクから読み出されます。on はディスクから読み出し、auto は 4 GiB を超える場合に読み出し、off はメモリに保持します。',
    },
  },
  zh: {
    title: '加载前的预计用量', estimated: '内存估算 · 随设置更新',
    ramTotal: 'RAM 合计', totalMemory: 'VRAM + RAM',
    workingSetHint: '仅所选模型 · 不含其他应用和操作系统文件缓存',
    fileCacheHint: 'RAM 合计包含运行辅助 RAM 和 RAM 卸载。读取模型文件或向 GPU 传输权重时，RAM 中还可能保留可回收的操作系统文件缓存。该缓存并非固定分配，因此不计入估算。系统监视器可能包含缓存或其他应用的内存；请保持其他任务相同，比较模型加载前后的增量。',
    vram: 'VRAM', ramOffload: 'RAM 卸载', ssdOffload: 'SSD 卸载',
    select: '选择模型和运行时后即可估算用量。', invalid: '完成有效的设置输入后更新估算。',
    loading: '计算中…', unknown: '无法估算', error: '无法计算资源用量。', retry: '重新估算用量',
    details: '估算详情', requiredVram: '请求的 VRAM', vramCapacity: 'VRAM 总量', capacity: '系统内存总量',
    hostMemory: '运行辅助 RAM', hostMemoryHelp: '运行辅助 RAM 说明',
    hostMemoryHint: '即使使用 GPU 运行也需要的系统内存，包含输入嵌入、工作缓冲区和运行时开销。',
    ramTotalHint: 'RAM 合计 = 运行辅助 RAM + RAM 卸载。', kv: 'KV 缓存',
    storedFiles: '已存储的模型文件', modelFiles: '主模型文件', auxiliaryFiles: '投影器、草稿模型和适配器文件', incomplete: '部分文件大小',
    exceedsMemory: '超出 VRAM 和 RAM 容量', exceedsVram: '请求的 VRAM 超出容量',
     scope: 'VRAM、运行辅助 RAM、RAM 卸载和 SSD 卸载是此配置的估算值，并非实测。RAM 卸载是在 VRAM 之后放入系统内存的模型/缓存数据，不含运行辅助 RAM。SSD 卸载是此配置从磁盘读取的模型/缓存估算部分——显式置于磁盘的权重加上超出 VRAM 和 RAM 容量的部分——并非安装大小。',
    capacityHint: '容量为本机的物理内存总量，未扣除其他应用和正在运行的模型所用的内存，因此加载时的可用内存可能更少。',
    filesHint: '已存储的模型文件是所选文件（含所有分片）在磁盘上已占用的大小，并非 SSD 卸载。加载不会复制文件，更改上下文或批次也不会改变其大小。',
    benchmark: '基准测试会覆盖部分设置，因此每次运行的内存用量可能不同。',
    notes: {
      approximate: '根据 GGUF 元数据和工作缓冲区估算得出，并非实测。运行时版本、驱动、内存映射和工作负载会影响实际及峰值用量。',
      automatic: '自动决定的运行时设置按运行时的默认行为估算，而非极端分配。指定明确的值可得到更具体的估算。',
      missing_metadata: '缺少估算所需的 GGUF 元数据，或无法读取。',
      unsupported_architecture: '此模型结构需要在运行时实测内存用量。',
      missing_files: '部分文件或分片缺失或无法读取，已存储文件的总量不完整。',
      auxiliary: '包含投影器、草稿模型或适配器的内存，其工作内存随工作负载变化。',
      shared_memory: '所选后端可能共享系统内存。VRAM 和 RAM 卸载不一定是独立的物理内存池。',
      advanced_options: '高级内存或分配选项使此配置无法得到可靠的估算。',
      capacity_unknown: '无法检测 VRAM 或系统内存总量，因此 VRAM、RAM 卸载和 SSD 卸载之间的分配并不确定。',
      placement_adjustment: '请求的 GPU 分配所需的 VRAM 超过设备容量。超出部分显示为此配置所需的 RAM 或 SSD 卸载，运行时不会自动转移。请在加载前调整 GPU 层数或卸载设置。',
       disk_offload: '放不进 VRAM 和 RAM 的部分，只有在运行时和设置允许时才能通过内存映射等基于磁盘的方式读取，生成会明显变慢，也可能加载失败。',
      lazy_offload: '符合条件的嵌入权重按 lazy-mode 设置从磁盘按需读取：on 从磁盘读取，auto 在超过 4 GiB 时从磁盘读取，off 则保留在内存中。',
    },
  },
};
