import type { Locale } from './i18n';
const runtimeCopy = {
  ko: { snapshot: '전체 모델 스냅샷 다운로드', engine: '추론 엔진', runtime: '런타임', choose: '런타임 선택', inherit: '런타임 기본값', options: '실행 및 요청 옵션', unsupported: '이 운영체제에서는 실행할 수 없습니다.', install: '격리 환경에 설치', register: '기존 Python 환경 등록', python: 'Python 실행 파일 경로', remove: '제거', all: '모든 런타임', compatibility: '모델 호환성', preview: '명령어 미리보기', import: '명령어 가져오기', changed: '모델과 호환되는 프로필로 전환했습니다.', files: '필수 파일이 누락되었습니다.', formats: '모델 형식', modalities: '지원 입력', media: '미디어 첨부', blocked: '이 모델은 첨부된 입력을 지원하지 않습니다.', reset: '값 지우기', adapters: 'LoRA 및 초안 모델', environment: '런타임 환경', loading: '런타임 정보를 확인하는 중입니다.', invalid: '옵션 형식과 허용 범위를 확인해 주세요.' },
  en: { snapshot: 'Download complete model snapshot', engine: 'Inference engine', runtime: 'Runtime', choose: 'Choose a runtime', inherit: 'Runtime default', options: 'Launch and request options', unsupported: 'Unavailable on this operating system.', install: 'Install isolated environment', register: 'Register existing Python environment', python: 'Python executable path', remove: 'Remove', all: 'All runtimes', compatibility: 'Model compatibility', preview: 'Command preview', import: 'Import command', changed: 'Switched to a profile compatible with the model.', files: 'Required files are missing.', formats: 'Model format', modalities: 'Supported inputs', media: 'Attach media', blocked: 'This model does not support the attached input.', reset: 'Clear value', adapters: 'LoRA and draft models', environment: 'Runtime environment', loading: 'Checking runtime information.', invalid: 'Check the option format and allowed range.' },
  ja: { snapshot: 'モデルの完全なスナップショットをダウンロード', engine: '推論エンジン', runtime: 'ランタイム', choose: 'ランタイムを選択', inherit: 'ランタイムの既定値', options: '起動とリクエストのオプション', unsupported: 'このOSでは実行できません。', install: '分離環境にインストール', register: '既存のPython環境を登録', python: 'Python実行ファイルのパス', remove: '削除', all: 'すべてのランタイム', compatibility: 'モデルの互換性', preview: 'コマンドのプレビュー', import: 'コマンドを取り込む', changed: 'モデルと互換性のあるプロファイルに切り替えました。', files: '必須ファイルが不足しています。', formats: 'モデル形式', modalities: '対応する入力', media: 'メディアを添付', blocked: 'このモデルは添付した入力に対応していません。', reset: '値を消去', adapters: 'LoRAとドラフトモデル', environment: 'ランタイム環境', loading: 'ランタイム情報を確認しています。', invalid: 'オプションの形式と許容範囲を確認してください。' },
  zh: { snapshot: '下载完整模型快照', engine: '推理引擎', runtime: '运行时', choose: '选择运行时', inherit: '运行时默认值', options: '启动和请求选项', unsupported: '无法在此操作系统上运行。', install: '安装隔离环境', register: '注册现有Python环境', python: 'Python可执行文件路径', remove: '移除', all: '所有运行时', compatibility: '模型兼容性', preview: '命令预览', import: '导入命令', changed: '已切换到与模型兼容的配置。', files: '缺少必需文件。', formats: '模型格式', modalities: '支持的输入', media: '附加媒体', blocked: '此模型不支持附加的输入。', reset: '清除值', adapters: 'LoRA和草稿模型', environment: '运行时环境', loading: '正在检查运行时信息。', invalid: '请检查选项格式和允许范围。' },
} satisfies Record<Locale, Record<string, string>>;

export const providerCopy = {
  ko: { ...runtimeCopy.ko, noOptions: "이 런타임은 이 항목에서 설정할 옵션을 제공하지 않습니다.", ready: "사용 가능", notReady: "확인 필요", noRuntimes: "이 엔진에 설치된 런타임이 없습니다. 위에서 설치하거나 기존 환경을 등록하세요.", launch: "실행 시 적용", request: "요청마다 적용", modelDefault: "모델 / 하드웨어 기본값", all: "모든 엔진", discoverTitle: 'Hugging Face 모델 찾아보기', discoverDescription: '모델 파일을 찾아 다운로드하고 실행 설정에서 런타임 호환성을 확인합니다.', discoverPlaceholder: '저장소 검색', discoverSelect: '모델 파일을 확인할 저장소를 선택하세요.', ggufPrerequisites: 'vLLM의 로컬 GGUF에는 일치하는 config와 토크나이저가 필요합니다. 같은 저장소에 동반 파일이 있으면 함께 받을 수 있습니다. 없으면 모델 관리에 추가하고 동반 파일을 별도로 준비하세요. 실행 설정에서 호환성을 확인합니다.', ggufCompanions: 'GGUF와 로컬 config·토크나이저 함께 다운로드' },
  en: { ...runtimeCopy.en, noOptions: "This runtime exposes no options in this category.", ready: "Ready", notReady: "Needs attention", noRuntimes: "No installed runtimes for this engine. Install or register one above.", launch: "At launch", request: "Per request", modelDefault: "Model / hardware default", all: "All engines", discoverTitle: 'Find models on Hugging Face', discoverDescription: 'Browse and download model files; runtime compatibility is checked during setup.', discoverPlaceholder: 'Search repositories', discoverSelect: 'Select a repository to inspect model files.', ggufPrerequisites: 'Local GGUF on vLLM requires matching config and tokenizer companions. Download them together when the same repository supplies them; otherwise keep the model in your library and prepare companions separately. Compatibility is checked during setup.', ggufCompanions: 'Download GGUF with local config and tokenizer' },
  ja: { ...runtimeCopy.ja, noOptions: "このランタイムはこの項目のオプションを公開していません。", ready: "使用可能", notReady: "確認が必要", noRuntimes: "このエンジンのランタイムがありません。インストールするか既存の環境を登録してください。", launch: "起動時", request: "リクエストごと", modelDefault: "モデル / ハードウェアの既定値", all: "すべてのエンジン", discoverTitle: 'Hugging Faceでモデルを探す', discoverDescription: 'モデルファイルを探してダウンロードし、起動設定でランタイムとの互換性を確認します。', discoverPlaceholder: 'リポジトリを検索', discoverSelect: 'モデルファイルを確認するリポジトリを選択してください。', ggufPrerequisites: 'vLLMでローカルGGUFを使うには一致するconfigとトークナイザーが必要です。同じリポジトリにあれば一緒にダウンロードできます。なければライブラリに保存し、関連ファイルを別途用意してください。起動設定で互換性を確認します。', ggufCompanions: 'GGUFとローカルconfig・トークナイザーをダウンロード' },
  zh: { ...runtimeCopy.zh, noOptions: "此运行时未提供这一类别的选项。", ready: "可用", notReady: "需要检查", noRuntimes: "此引擎尚未安装运行时。请在上方安装或注册现有环境。", launch: "启动时应用", request: "每次请求应用", modelDefault: "模型 / 硬件默认值", all: "所有引擎", discoverTitle: '在Hugging Face查找模型', discoverDescription: '浏览并下载模型文件，在运行设置中检查运行时兼容性。', discoverPlaceholder: '搜索仓库', discoverSelect: '选择仓库以查看模型文件。', ggufPrerequisites: '在vLLM使用本地GGUF需要匹配的config和分词器。同一仓库提供这些文件时可以一起下载；否则先将模型保存在模型库中，并另行准备关联文件。在运行设置中检查兼容性。', ggufCompanions: '下载GGUF及本地config和分词器' },
} satisfies Record<Locale, Record<string, string>>;
