import type { Locale } from '../../shared/i18n/i18n';

const en = {
  intro: 'Let other apps use models on this computer. You do not need this server for chat inside AioLM.',
  steps: ['Start the server', 'Load a model', 'Enter the connection details in your app'],
  stopped: 'Start the server when you want to connect another app.',
  running: 'Listening on this computer. Stopping the API keeps your models loaded.',
  models: 'Available models',
  modelsOff: 'Start the API to see the models available to other apps.',
  modelsEmpty: 'No model is loaded yet. Open the model library and load one to handle requests.',
  modelsLoading: 'The model is loading. It will appear here when ready.',
  modelsChecking: 'Checking available models…',
  modelsUnavailable: 'The model list could not be read. Try refreshing it.',
  openModels: 'Open model library', refresh: 'Refresh models',
  modelHint: 'Use this model ID in the other app.', copyModel: 'Copy model ID',
  connection: 'Connect another app', connectionHint: 'Copy these values into the connection settings of your app.',
  format: 'Connection format', formatHint: 'Choose the format your app expects. Both use this same server.',
  key: 'API key', keyHint: 'Copy the key while the server is running. It changes when AioLM is reopened.',
  settings: 'Server settings', examples: 'API reference & examples', language: 'Example language', copyExample: 'Copy example',
  exampleHint: 'Replace <LOCAL_API_KEY> with your key and <MODEL_ID> with an ID above.',
  endpoint: 'Endpoint', method: 'Method', diagnostics: 'Open model diagnostics',
};

export const apiServerCopy: Record<Locale, typeof en> = {
  en,
  ko: {
    intro: '다른 앱에서 이 컴퓨터의 모델을 사용하려면 켜세요. AioLM 내부 채팅에는 이 서버가 필요하지 않습니다.',
    steps: ['서버 시작', '모델 로드', '외부 앱에 연결 정보 입력'],
    stopped: '외부 앱을 연결할 때 서버를 시작하세요.',
    running: '이 컴퓨터에서 연결을 받습니다. API를 중지해도 모델은 로드된 상태로 유지됩니다.',
    models: '사용 가능한 모델', modelsOff: 'API를 시작하면 외부 앱에서 사용할 수 있는 모델이 표시됩니다.',
    modelsEmpty: '아직 로드된 모델이 없습니다. 모델 목록을 열어 사용할 모델을 로드하세요.',
    modelsLoading: '모델을 로드하고 있습니다. 준비가 끝나면 여기에 표시됩니다.',
    modelsChecking: '사용 가능한 모델 확인 중…', modelsUnavailable: '모델 목록을 확인하지 못했습니다. 새로고침해 주세요.',
    openModels: '모델 목록 열기', refresh: '모델 새로고침', modelHint: '외부 앱의 모델 항목에 이 ID를 입력하세요.', copyModel: '모델 ID 복사',
    connection: '외부 앱에 연결', connectionHint: '사용할 앱의 연결 설정에 아래 값을 입력하세요.',
    format: '연결 형식', formatHint: '연결할 앱이 요구하는 형식을 선택하세요. 두 형식 모두 같은 서버를 사용합니다.',
    key: 'API 키', keyHint: '서버가 실행 중일 때 키를 복사할 수 있습니다. AioLM을 다시 열면 키가 바뀝니다.',
    settings: '서버 설정', examples: 'API 문서와 예제', language: '예제 언어', copyExample: '예제 복사',
    exampleHint: '<LOCAL_API_KEY>는 복사한 키로, <MODEL_ID>는 위 모델 ID로 바꿔 주세요.',
    endpoint: '엔드포인트', method: '메서드', diagnostics: '모델 진단 열기',
  },
  ja: {
    intro: '他のアプリからこのコンピューターのモデルを使うときに起動します。AioLM内のチャットには不要です。',
    steps: ['サーバーを起動', 'モデルを読み込む', '他のアプリに接続情報を入力'],
    stopped: '他のアプリを接続するときにサーバーを起動してください。',
    running: 'このコンピューターで接続を受け付けています。APIを停止してもモデルは読み込まれたままです。',
    models: '利用可能なモデル', modelsOff: 'APIを起動すると、他のアプリで利用できるモデルが表示されます。',
    modelsEmpty: 'モデルが読み込まれていません。モデル一覧から利用するモデルを読み込んでください。',
    modelsLoading: 'モデルを読み込み中です。準備ができるとここに表示されます。',
    modelsChecking: '利用可能なモデルを確認中…', modelsUnavailable: 'モデル一覧を取得できませんでした。更新してください。',
    openModels: 'モデル一覧を開く', refresh: 'モデルを更新', modelHint: '他のアプリのモデル欄にこのIDを入力してください。', copyModel: 'モデルIDをコピー',
    connection: '他のアプリに接続', connectionHint: '利用するアプリの接続設定に次の値を入力してください。',
    format: '接続形式', formatHint: '接続先アプリが必要とする形式を選びます。どちらも同じサーバーを使います。',
    key: 'APIキー', keyHint: 'サーバーの実行中にキーをコピーできます。AioLMを開き直すとキーが変わります。',
    settings: 'サーバー設定', examples: 'APIリファレンスと例', language: 'サンプル言語', copyExample: '例をコピー',
    exampleHint: '<LOCAL_API_KEY>をキーに、<MODEL_ID>を上のモデルIDに置き換えてください。',
    endpoint: 'エンドポイント', method: 'メソッド', diagnostics: 'モデル診断を開く',
  },
  zh: {
    intro: '需要让其他应用使用此电脑上的模型时，启动此服务器。AioLM 内部聊天无需启动它。',
    steps: ['启动服务器', '加载模型', '在其他应用中填写连接信息'],
    stopped: '需要连接其他应用时，请启动服务器。',
    running: '正在此电脑上接收连接。停止 API 后，模型仍保持加载。',
    models: '可用模型', modelsOff: '启动 API 后，会显示其他应用可使用的模型。',
    modelsEmpty: '尚未加载模型。请打开模型列表并加载要使用的模型。',
    modelsLoading: '正在加载模型。就绪后会显示在此处。',
    modelsChecking: '正在检查可用模型…', modelsUnavailable: '无法读取模型列表，请刷新重试。',
    openModels: '打开模型列表', refresh: '刷新模型', modelHint: '在其他应用的模型字段中填写此 ID。', copyModel: '复制模型 ID',
    connection: '连接其他应用', connectionHint: '在要使用的应用的连接设置中填写以下信息。',
    format: '连接格式', formatHint: '选择应用需要的格式。两种格式都使用同一个服务器。',
    key: 'API 密钥', keyHint: '服务器运行时可复制密钥。重新打开 AioLM 后密钥会更改。',
    settings: '服务器设置', examples: 'API 文档与示例', language: '示例语言', copyExample: '复制示例',
    exampleHint: '将 <LOCAL_API_KEY> 替换为密钥，将 <MODEL_ID> 替换为上方的模型 ID。',
    endpoint: '端点', method: '方法', diagnostics: '打开模型诊断',
  },
};
