//! Architecture lists copied from upstream source at a pinned release.
//!
//! They are a fallback for when an installed engine cannot be asked for its own
//! registry. A probed runtime reports the list of the version actually
//! installed, which always takes precedence (see `providers::compat`).
//!
//! Generated from vLLM v0.31.0 `vllm/model_executor/models/registry.py` and
//! the `mlx_vlm/models` package directories of mlx-vlm v0.7.6.

pub const VLLM_SNAPSHOT_VERSION: &str = "0.31.0";
pub const MLX_VLM_SNAPSHOT_VERSION: &str = "0.7.6";

/// vllm-metal v0.30.0 `docs/supported_models.md`, intersected with the
/// mlx-lm revision pinned by that tag (9e6acca). This is deliberately separate
/// from vLLM's GPU ModelRegistry: Metal actually loads through MLX.
pub const VLLM_METAL_SNAPSHOT_VERSION: &str = "0.30.0";
pub const VLLM_METAL_TEXT_MODEL_TYPES: &[&str] = &[
    "qwen2",
    "qwen3",
    "qwen3_moe",
    "qwen3_5",
    "qwen3_5_moe",
    "qwen3_next",
    "lfm2",
    "nemotron_h",
    "granitemoehybrid",
    "gemma4",
    "gemma4_text",
    "gemma3",
    "gemma3_text",
    "llama",
    "mistral",
    "stablelm",
    "phi",
    "phi3",
    "gpt_oss",
    "minicpm3",
    "glm4_moe_lite",
    "smollm3",
    "granite",
    "exaone4",
    "laguna",
    "hunyuan",
    "hunyuan_v1_dense",
    "minimax_m2",
    "olmo2",
    "olmoe",
    "olmo3",
];
/// Native image adapters in `v1/model_adapter.py`; Qwen3.5 FP8 conditional
/// wrappers use the text backbone instead. Gemma4's override is text-only.
pub const VLLM_METAL_IMAGE_MODEL_TYPES: &[&str] = &["qwen3_vl", "qwen3_5", "paddleocr_vl"];
/// Native speech-to-text in `vllm_metal/stt/detection.py` (`_STT_MODEL_TYPES`)
/// with constructors in `vllm_metal/stt/registry.py`. Qwen3-ASR is
/// transcription-only; translation needs Whisper. See `docs/stt.md`.
pub const VLLM_METAL_TRANSCRIPTION_MODEL_TYPES: &[&str] = &["qwen3_asr", "whisper"];
pub const VLLM_METAL_TRANSLATION_MODEL_TYPES: &[&str] = &["whisper"];
/// STT `model_type`/`architectures` pairs from the plugin's STT registry and
/// core v0.30.0 `registry.py`. `Qwen3ASRRealtimeGeneration` is realtime-only
/// and has no file-transcription binding here.
pub const VLLM_METAL_TRANSCRIPTION_ARCHITECTURES: &[(&str, &[&str])] = &[
    ("whisper", &["WhisperForConditionalGeneration"]),
    ("qwen3_asr", &["Qwen3ASRForConditionalGeneration"]),
];
/// App-supported /v1/embeddings families evidenced in text_embedding_pooling.md.
/// Rerank/classify and BGE sparse /pooling are outside the app's task contract.
pub const VLLM_METAL_EMBEDDING_MODEL_TYPES: &[&str] = &["qwen3", "xlm-roberta", "roberta"];

/// Model-type/architecture pairs from core v0.30.0 registry.py and the
/// plugin's MLX load path. An installed core must also register the named
/// architecture; neither condition alone proves Metal compatibility.
pub const VLLM_METAL_ARCHITECTURES: &[(&str, &[&str])] = &[
    (
        "llama",
        &["LlamaForCausalLM", "LLaMAForCausalLM", "LlamaModel"],
    ),
    ("mistral", &["MistralForCausalLM", "MistralModel"]),
    ("qwen2", &["Qwen2ForCausalLM", "Qwen2Model"]),
    ("qwen3", &["Qwen3ForCausalLM"]),
    ("qwen3_moe", &["Qwen3MoeForCausalLM"]),
    ("qwen3_next", &["Qwen3NextForCausalLM"]),
    (
        "qwen3_5",
        &["Qwen3_5ForCausalLM", "Qwen3_5ForConditionalGeneration"],
    ),
    (
        "qwen3_5_moe",
        &[
            "Qwen3_5MoeForCausalLM",
            "Qwen3_5MoeForConditionalGeneration",
        ],
    ),
    ("qwen3_vl", &["Qwen3VLForConditionalGeneration"]),
    ("paddleocr_vl", &["PaddleOCRVLForConditionalGeneration"]),
    ("lfm2", &["Lfm2ForCausalLM"]),
    (
        "nemotron_h",
        &["NemotronHForCausalLM", "NemotronHPuzzleForCausalLM"],
    ),
    ("granitemoehybrid", &["GraniteMoeHybridForCausalLM"]),
    (
        "gemma4",
        &["Gemma4ForCausalLM", "Gemma4ForConditionalGeneration"],
    ),
    ("gemma4_text", &["Gemma4ForCausalLM"]),
    (
        "gemma3",
        &["Gemma3ForCausalLM", "Gemma3ForConditionalGeneration"],
    ),
    ("gemma3_text", &["Gemma3ForCausalLM", "Gemma3TextModel"]),
    ("stablelm", &["StableLmForCausalLM"]),
    ("phi", &["PhiForCausalLM"]),
    ("phi3", &["Phi3ForCausalLM"]),
    ("gpt_oss", &["GptOssForCausalLM"]),
    ("minicpm3", &["MiniCPM3ForCausalLM"]),
    ("glm4_moe_lite", &["Glm4MoeLiteForCausalLM"]),
    ("smollm3", &["SmolLM3ForCausalLM"]),
    ("granite", &["GraniteForCausalLM", "GraniteSWAForCausalLM"]),
    ("exaone4", &["Exaone4ForCausalLM"]),
    ("laguna", &["LagunaForCausalLM"]),
    ("hunyuan", &["HunYuanDenseV1ForCausalLM"]),
    ("hunyuan_v1_dense", &["HunYuanDenseV1ForCausalLM"]),
    ("minimax_m2", &["MiniMaxM2ForCausalLM"]),
    ("olmo2", &["Olmo2ForCausalLM"]),
    ("olmoe", &["OlmoeForCausalLM"]),
    ("olmo3", &["Olmo3ForCausalLM"]),
    ("xlm-roberta", &["XLMRobertaModel"]),
    ("roberta", &["RobertaModel"]),
];

/// `_TEXT_GENERATION_MODELS` keys.
pub const VLLM_TEXT_GENERATION: &[&str] = &[
    "AXK1ForCausalLM",
    "AfmoeForCausalLM",
    "ApertusForCausalLM",
    "ArceeForCausalLM",
    "BailingMoeForCausalLM",
    "BailingMoeV2ForCausalLM",
    "BailingMoeV2_5ForCausalLM",
    "BailingMoeV3ForCausalLM",
    "BloomForCausalLM",
    "ChatGLMForConditionalGeneration",
    "ChatGLMModel",
    "Cohere2ForCausalLM",
    "Cohere2MoeForCausalLM",
    "CohereForCausalLM",
    "CwmForCausalLM",
    "DbrxForCausalLM",
    "DeciLMForCausalLM",
    "DeepseekForCausalLM",
    "DeepseekV2ForCausalLM",
    "DeepseekV32ForCausalLM",
    "DeepseekV3ForCausalLM",
    "DeepseekV4ForCausalLM",
    "Ernie4_5ForCausalLM",
    "Ernie4_5_MoeForCausalLM",
    "Exaone4ForCausalLM",
    "ExaoneForCausalLM",
    "ExaoneMoeForCausalLM",
    "FalconForCausalLM",
    "FalconH1ForCausalLM",
    "FalconMambaForCausalLM",
    "GPT2LMHeadModel",
    "GPTJForCausalLM",
    "GPTNeoXForCausalLM",
    "Gemma2ForCausalLM",
    "Gemma3ForCausalLM",
    "Gemma3nForCausalLM",
    "Gemma4ForCausalLM",
    "GemmaForCausalLM",
    "Glm4ForCausalLM",
    "Glm4MoeForCausalLM",
    "Glm4MoeLiteForCausalLM",
    "Glm5NextForCausalLM",
    "GlmForCausalLM",
    "GlmMoeDsaForCausalLM",
    "GptOssForCausalLM",
    "GraniteForCausalLM",
    "GraniteMoeForCausalLM",
    "GraniteMoeHybridForCausalLM",
    "GraniteMoeSWAForCausalLM",
    "GraniteMoeSharedForCausalLM",
    "GraniteSWAForCausalLM",
    "HCXVisionV2ForCausalLM",
    "HYV3ForCausalLM",
    "HYV4ForCausalLM",
    "HrmTextForCausalLM",
    "HyperCLOVAXForCausalLM",
    "IQuestCoderForCausalLM",
    "IQuestLoopCoderForCausalLM",
    "InklingForCausalLM",
    "InklingForConditionalGeneration",
    "InternLM2ForCausalLM",
    "InternLM3ForCausalLM",
    "Jais2ForCausalLM",
    "JambaForCausalLM",
    "K2HorizonForCausalLM",
    "KimiLinearForCausalLM",
    "LLaMAForCausalLM",
    "LagunaForCausalLM",
    "Lfm2ForCausalLM",
    "Lfm2MoeForCausalLM",
    "Llama4ForCausalLM",
    "LlamaForCausalLM",
    "LongcatFlashForCausalLM",
    "LongcatFlashNgramForCausalLM",
    "Mamba2ForCausalLM",
    "MambaForCausalLM",
    "MellumForCausalLM",
    "MiMoForCausalLM",
    "MiMoV2FlashForCausalLM",
    "MiMoV2ForCausalLM",
    "MiniCPM3ForCausalLM",
    "MiniCPMForCausalLM",
    "MiniMaxM2ForCausalLM",
    "MiniMaxM3SparseForCausalLM",
    "Ministral3ForCausalLM",
    "MistralForCausalLM",
    "MistralLarge3ForCausalLM",
    "MixtralForCausalLM",
    "MuseGlimmerForCausalLM",
    "NemotronForCausalLM",
    "NemotronHForCausalLM",
    "NemotronHPuzzleForCausalLM",
    "OPTForCausalLM",
    "OlmoHybridForCausalLM",
    "OlmoeForCausalLM",
    "OrionForCausalLM",
    "PanguEmbeddedForCausalLM",
    "PanguProMoEV2ForCausalLM",
    "PanguUltraMoEForCausalLM",
    "Param2MoEForCausalLM",
    "Phi3ForCausalLM",
    "PhiForCausalLM",
    "PhiMoEForCausalLM",
    "Plamo3ForCausalLM",
    "Qwen2ForCausalLM",
    "Qwen2MoeForCausalLM",
    "Qwen3ForCausalLM",
    "Qwen3MoeForCausalLM",
    "Qwen3NextForCausalLM",
    "Qwen3_5ForCausalLM",
    "Qwen3_5MoeForCausalLM",
    "Qwen4ExpForCausalLM",
    "Rnj1ForCausalLM",
    "SarvamMLAForCausalLM",
    "SarvamMoEForCausalLM",
    "SeedOssForCausalLM",
    "SolarForCausalLM",
    "StableLmForCausalLM",
    "Step1ForCausalLM",
    "Step3TextForCausalLM",
    "Step3p5ForCausalLM",
    "TeleChat2ForCausalLM",
    "TeleChat3ForCausalLM",
    "TeleFLMForCausalLM",
    "Zamba2ForCausalLM",
];
/// `_MULTIMODAL_MODELS` keys.
pub const VLLM_MULTIMODAL: &[&str] = &[
    "AriaForConditionalGeneration",
    "AudioFlamingo3ForConditionalGeneration",
    "BagelForConditionalGeneration",
    "BailingMoeV3VLForConditionalGeneration",
    "BeeForConditionalGeneration",
    "Blip2ForConditionalGeneration",
    "Cohere2VisionForConditionalGeneration",
    "CohereAsrForConditionalGeneration",
    "CohereCompassForConditionalGeneration",
    "Cosmos3EdgeForConditionalGeneration",
    "Cosmos3ForConditionalGeneration",
    "DeepseekOCR2ForCausalLM",
    "DeepseekOCRForCausalLM",
    "DeepseekV41ForCausalLM",
    "DeepseekV4ForConditionalGeneration",
    "DeepseekVLV2ForCausalLM",
    "DiffusionGemmaForBlockDiffusion",
    "Dots3NoteForCausalLM",
    "DotsOCRForCausalLM",
    "Eagle2_5_VLForConditionalGeneration",
    "Ernie4_5_VLMoeForConditionalGeneration",
    "Exaone4_5_ForConditionalGeneration",
    "FireRedASR2ForConditionalGeneration",
    "FunASRForConditionalGeneration",
    "FunAudioChatForConditionalGeneration",
    "GLM4VForCausalLM",
    "Gemma3ForConditionalGeneration",
    "Gemma3nForConditionalGeneration",
    "Gemma4ForConditionalGeneration",
    "Gemma4UnifiedForConditionalGeneration",
    "Glm4vForConditionalGeneration",
    "Glm4vMoeForConditionalGeneration",
    "Glm5NextForConditionalGeneration",
    "GlmAsrForConditionalGeneration",
    "GlmOcrForConditionalGeneration",
    "Granite4VisionForConditionalGeneration",
    "GraniteSpeechForConditionalGeneration",
    "GraniteSpeechPlusForConditionalGeneration",
    "H2OVLChatModel",
    "HfMoondream",
    "Idefics3ForConditionalGeneration",
    "InternS1ForConditionalGeneration",
    "InternS1ProForConditionalGeneration",
    "InternS2MobiusForConditionalGeneration",
    "InternS2PreviewForConditionalGeneration",
    "InternVLChatModel",
    "InternVLForConditionalGeneration",
    "IsaacForConditionalGeneration",
    "KananaVForConditionalGeneration",
    "KeyeForConditionalGeneration",
    "KeyeVL1_5ForConditionalGeneration",
    "KimiK25ForConditionalGeneration",
    "KimiK3ForConditionalGeneration",
    "KimiVLForConditionalGeneration",
    "Lfm2VlForConditionalGeneration",
    "LightOnOCRForConditionalGeneration",
    "Llama4ForConditionalGeneration",
    "Llama_Nemotron_Nano_VL",
    "LlavaForConditionalGeneration",
    "LlavaNextForConditionalGeneration",
    "LlavaNextVideoForConditionalGeneration",
    "LlavaOnevision2ForConditionalGeneration",
    "LlavaOnevisionForConditionalGeneration",
    "MiDashengLMModel",
    "MiMoV2OmniForCausalLM",
    "MiniCPMO",
    "MiniCPMV",
    "MiniCPMV4_6ForConditionalGeneration",
    "MiniMaxM3SparseForConditionalGeneration",
    "Mistral3ForConditionalGeneration",
    "Molmo2ForConditionalGeneration",
    "MolmoForCausalLM",
    "Moondream3ForCausalLM",
    "MoonshotKimiaForCausalLM",
    "MossAudioModel",
    "MossTranscribeDiarizeForConditionalGeneration",
    "MuseGlimmerForConditionalGeneration",
    "NVLM_D",
    "NemotronH_Nano_Omni_Reasoning_V3",
    "NemotronH_Nano_VL_V2",
    "NemotronH_Omni_Reasoning_V3",
    "NemotronH_Super_Omni_Reasoning_V3",
    "NemotronParseForConditionalGeneration",
    "OpenCUAForConditionalGeneration",
    "OpenPanguVLForConditionalGeneration",
    "OpenVLAForActionPrediction",
    "Ovis",
    "Ovis2_5",
    "Ovis2_6ForCausalLM",
    "Ovis2_6_MoeForCausalLM",
    "PaddleOCRVLForConditionalGeneration",
    "PaliGemmaForConditionalGeneration",
    "Phi3VForCausalLM",
    "Phi4ForCausalLMV",
    "Phi4MMForCausalLM",
    "PixtralForConditionalGeneration",
    "QianfanOCRForConditionalGeneration",
    "Qwen2AudioForConditionalGeneration",
    "Qwen2VLForConditionalGeneration",
    "Qwen2_5OmniForConditionalGeneration",
    "Qwen2_5OmniModel",
    "Qwen2_5_VLForConditionalGeneration",
    "Qwen3ASRForConditionalGeneration",
    "Qwen3ASRRealtimeGeneration",
    "Qwen3OmniMoeForConditionalGeneration",
    "Qwen3VLForConditionalGeneration",
    "Qwen3VLMoeForConditionalGeneration",
    "Qwen3_5ForConditionalGeneration",
    "Qwen3_5MoeForConditionalGeneration",
    "Qwen4ExpForConditionalGeneration",
    "RForConditionalGeneration",
    "SkyworkR1VChatModel",
    "SmolVLMForConditionalGeneration",
    "Step3VLForConditionalGeneration",
    "Step3p7ForConditionalGeneration",
    "StepVLForConditionalGeneration",
    "UltravoxModel",
    "UnlimitedOCRForCausalLM",
    "VoxtralForConditionalGeneration",
    "VoxtralRealtimeGeneration",
    "WhisperForConditionalGeneration",
];
/// `_EMBEDDING_MODELS` keys.
pub const VLLM_EMBEDDING: &[&str] = &[
    "BertForMaskedLM",
    "BertModel",
    "BertSpladeSparseEmbeddingModel",
    "BgeM3EmbeddingModel",
    "CLIPModel",
    "ColPaliForRetrieval",
    "DeciLMForCausalLM",
    "DeepseekV3BidirectionalModel",
    "Gemma2Model",
    "Gemma3TextModel",
    "GlmForCausalLM",
    "GteModel",
    "GteNewModel",
    "JinaEmbeddingsV5Model",
    "LlamaBidirectionalModel",
    "LlamaModel",
    "LlamaNemotronVLModel",
    "LlavaNextForConditionalGeneration",
    "MistralModel",
    "ModernBertModel",
    "NomicBertModel",
    "Phi3ForCausalLM",
    "Phi3VForCausalLM",
    "Qwen2ForCausalLM",
    "Qwen2Model",
    "Qwen2VLForConditionalGeneration",
    "RobertaForMaskedLM",
    "RobertaModel",
    "SiglipModel",
    "TeleChat2ForCausalLM",
    "Terratorch",
    "VoyageQwen3BidirectionalEmbedModel",
    "XLMRobertaModel",
];
/// `_TRANSFORMERS_SUPPORTED_MODELS` keys (served through the Transformers backend).
pub const VLLM_TRANSFORMERS_BACKEND: &[&str] = &[
    "Emu3ForConditionalGeneration",
    "FlexOlmoForCausalLM",
    "GPTBigCodeForCausalLM",
    "HunYuanDenseV1ForCausalLM",
    "HunYuanMoEV1ForCausalLM",
    "HunYuanVLForConditionalGeneration",
    "NanbeigeForCausalLM",
    "Olmo2ForCausalLM",
    "Olmo3ForCausalLM",
    "OlmoForCausalLM",
    "SmolLM3ForCausalLM",
    "Starcoder2ForCausalLM",
    "VaultGemmaForCausalLM",
    "VibeVoiceAsrForConditionalGeneration",
];
/// `mlx_vlm/models/<model_type>` package names.
pub const MLX_VLM_MODEL_TYPES: &[&str] = &[
    "afm7",
    "afmoe",
    "apertus",
    "aya_vision",
    "baichuan_m1",
    "bailing_moe",
    "bailing_moe_linear",
    "bert",
    "bitnet",
    "bonsai",
    "cohere",
    "cohere2",
    "cohere2_moe",
    "cohere_compass",
    "colidefics3",
    "colqwen2_5",
    "dbrx",
    "decider2",
    "deepseek",
    "deepseek_v2",
    "deepseek_v3",
    "deepseek_v32",
    "deepseek_v4",
    "deepseek_v41",
    "deepseek_vl_v2",
    "deepseekocr",
    "deepseekocr_2",
    "diffusion_gemma",
    "dinov2",
    "dots1",
    "dots_ocr",
    "ernie4_5",
    "ernie4_5_moe",
    "ernie4_5_moe_vl",
    "ernie_image",
    "exaone",
    "exaone4",
    "exaone_moe",
    "falcon_h1",
    "falcon_ocr",
    "falcon_perception",
    "fastvlm",
    "florence2",
    "flux2",
    "gemma",
    "gemma2",
    "gemma3",
    "gemma3_embedding",
    "gemma3_text",
    "gemma3n",
    "gemma4",
    "gemma4_text",
    "gemma4_unified",
    "gliner2_5",
    "glm",
    "glm4",
    "glm4_moe",
    "glm4_moe_lite",
    "glm4v",
    "glm4v_moe",
    "glm5_next",
    "glm_moe_dsa",
    "glm_ocr",
    "got",
    "gpt2",
    "gpt_bigcode",
    "gpt_neox",
    "gpt_oss",
    "granite",
    "granite4_vision",
    "granite_vision",
    "granitemoe",
    "granitemoehybrid",
    "helium",
    "hrm_text",
    "hunyuan",
    "hunyuan_v1_dense",
    "hunyuan_vl",
    "hy_v4",
    "idefics2",
    "idefics3",
    "ideogram4",
    "indic_ocr",
    "inkling",
    "internlm2",
    "internlm3",
    "internvl",
    "internvl_chat",
    "iquestloopcoder",
    "jamba",
    "jina_vlm",
    "k2_horizon",
    "kimi_k25",
    "kimi_k3",
    "kimi_linear",
    "kimi_vl",
    "klear",
    "laguna",
    "laya",
    "lfm2",
    "lfm2_colbert",
    "lfm2_embedding",
    "lfm2_encoder",
    "lfm2_moe",
    "lfm2_vl",
    "lille_130m",
    "limite",
    "llada2_moe",
    "llada_image",
    "llama",
    "llama4",
    "llama4_text",
    "llama_bidirec",
    "llama_nemotron_vl_embedding",
    "llava",
    "llava_bunny",
    "llava_next",
    "llava_onevision",
    "llmjpvl",
    "locateanything",
    "longcat_flash",
    "longcat_flash_ngram",
    "longcat_flash_sparse",
    "mage_flow",
    "mage_vl",
    "mamba",
    "mamba2",
    "mellum",
    "mimo",
    "mimo_v2",
    "mimo_v2_flash",
    "ming_image",
    "minicpm",
    "minicpm3",
    "minicpmo",
    "minicpmv4_6",
    "minimax",
    "minimax_h3",
    "minimax_m3",
    "minimax_m3_vl",
    "ministral3",
    "ministral3_embedding",
    "mistral3",
    "mistral4",
    "mistral_large3",
    "mixtral",
    "mllama",
    "modernbert",
    "moge3",
    "molmo",
    "molmo2",
    "molmo_point",
    "moondream2",
    "moondream3",
    "multi_modality",
    "muse_glimmer",
    "nanochat",
    "nemotron",
    "nemotron_h",
    "nemotron_h_nano_omni",
    "nemotron_labs_diffusion",
    "nemotron_nas",
    "nemotron_parse",
    "nemotron_voicechat",
    "olmo",
    "olmo2",
    "olmo3",
    "olmoe",
    "openai_privacy_filter",
    "openelm",
    "paddleocr_vl",
    "paligemma",
    "phi",
    "phi3",
    "phi3_v",
    "phi3small",
    "phi4_siglip",
    "phi4mm",
    "phimoe",
    "phixtral",
    "pixtral",
    "plamo",
    "plamo2",
    "plamo2vl",
    "pp_doclayout_v3",
    "prism_hadamard_qwen35",
    "qwen",
    "qwen2",
    "qwen2_5_vl",
    "qwen2_moe",
    "qwen2_vl",
    "qwen3",
    "qwen3_5",
    "qwen3_5_moe",
    "qwen3_5_moe_text",
    "qwen3_5_text",
    "qwen3_embedding",
    "qwen3_moe",
    "qwen3_next",
    "qwen3_omni_moe",
    "qwen3_vl",
    "qwen3_vl_embedding",
    "qwen3_vl_moe",
    "qwen4_exp",
    "qwen_image",
    "recurrent_gemma",
    "rfdetr",
    "rt_detr_v2",
    "rwkv7",
    "sam3",
    "sam3_1",
    "sam3d_body",
    "sam3d_objects",
    "sapiens2",
    "seed_oss",
    "siglip",
    "smollm3",
    "smolvlm",
    "solar_open",
    "spark2_5",
    "stablelm",
    "starcoder2",
    "step3p5",
    "step3p7",
    "telechat3",
    "unlimited_ocr",
    "video_depth_anything",
    "xlm_roberta",
    "yolo11",
    "youtu_llm",
    "youtu_vl",
    "z1t",
    "z_image",
    "zaya1_vl",
];

/// `mlx_vlm.utils.MODEL_REMAPPING`: config `model_type` spellings mapped to
/// the package that implements them.
pub const MLX_VLM_MODEL_TYPE_ALIASES: &[(&str, &str)] = &[
    ("moondream1", "moondream2"),
    ("llava_qwen2", "fastvlm"),
    ("llava-qwen2", "llava_bunny"),
    ("bunny-llama", "llava_bunny"),
    ("lfm2-vl", "lfm2_vl"),
    ("cohere2_vision", "aya_vision"),
    ("jvlm", "jina_vlm"),
    ("phi4-siglip", "phi4_siglip"),
    ("sam3_video", "sam3"),
    ("sam3.1_video", "sam3_1"),
    ("granite-vision", "granite_vision"),
    ("granite4-vision", "granite4_vision"),
    ("granite4_vision", "granite4_vision"),
    ("rf-detr", "rfdetr"),
    ("dinov2_with_registers", "dinov2"),
    ("falcon-perception", "falcon_perception"),
    ("nemotronh_nano_omni_reasoning_v3", "nemotron_h_nano_omni"),
    ("cohere2moe", "cohere2_moe"),
    ("unlimited-ocr", "unlimited_ocr"),
    ("mistral", "llama"),
    ("phi-msft", "phixtral"),
    ("falcon_mamba", "mamba"),
    ("joyai_llm_flash", "deepseek_v3"),
    ("kimi_k2", "deepseek_v3"),
    ("minimax_m2", "minimax"),
    ("iquestcoder", "llama"),
    ("nemotron-nas", "nemotron_nas"),
    ("inkling_mm_model", "inkling"),
    ("lille-130m", "lille_130m"),
];

/// `mlx_vlm/models` packages that are not chat text generators in mlx-vlm
/// v0.7.6, read from each package's README and model class: image generation
/// pipelines (`is_image_generation_model`), segmentation, detection, depth,
/// pose and layout predictors, classifiers, encoders, the realtime-only voice
/// model, the decision model, a helper package without a `Model`, and the
/// embedding-only packages below. Loading one as `--model` cannot answer chat.
pub const MLX_VLM_NON_GENERATIVE_MODEL_TYPES: &[&str] = &[
    "bert",
    "bonsai",
    "colidefics3",
    "colqwen2_5",
    "decider2",
    "dinov2",
    "ernie_image",
    "falcon_perception",
    "flux2",
    "gemma3_embedding",
    "gliner2_5",
    "ideogram4",
    "indic_ocr",
    "lfm2_colbert",
    "lfm2_embedding",
    "lfm2_encoder",
    "llada_image",
    "llama_bidirec",
    "llama_nemotron_vl_embedding",
    "mage_flow",
    "ming_image",
    "ministral3_embedding",
    "mistral4",
    "modernbert",
    "moge3",
    "nemotron_voicechat",
    "openai_privacy_filter",
    "pp_doclayout_v3",
    "qwen3_embedding",
    "qwen3_vl_embedding",
    "qwen_image",
    "rfdetr",
    "rt_detr_v2",
    "sam3",
    "sam3_1",
    "sam3d_body",
    "sam3d_objects",
    "sapiens2",
    "siglip",
    "video_depth_anything",
    "xlm_roberta",
    "yolo11",
    "z_image",
];

/// Packages whose `Model` returns `pooling.EmbeddingOutput`, i.e. what
/// `mlx_vlm.embedding_loader.load_embedding_model` can serve.
pub const MLX_VLM_EMBEDDING_MODEL_TYPES: &[&str] = &[
    "bert",
    "colidefics3",
    "colqwen2_5",
    "gemma3_embedding",
    "lfm2_colbert",
    "lfm2_embedding",
    "llama_bidirec",
    "llama_nemotron_vl_embedding",
    "ministral3_embedding",
    "modernbert",
    "qwen3_embedding",
    "qwen3_vl_embedding",
    "siglip",
    "xlm_roberta",
];

/// `mlx_vlm.embedding_loader.EMBEDDING_MODEL_REMAPPING`.
pub const MLX_VLM_EMBEDDING_MODEL_TYPE_ALIASES: &[(&str, &str)] = &[
    ("qwen3", "qwen3_embedding"),
    ("gemma3_text", "gemma3_embedding"),
    ("lfm2", "lfm2_embedding"),
    ("ministral3", "ministral3_embedding"),
    ("xlm-roberta", "xlm_roberta"),
];

/// Generative packages with an audio encoder (`AudioConfig` in their
/// `config.py`). Every other package ignores audio parts.
pub const MLX_VLM_AUDIO_MODEL_TYPES: &[&str] = &[
    "gemma3n",
    "gemma4",
    "gemma4_unified",
    "inkling",
    "mimo_v2",
    "minicpmo",
    "nemotron_h_nano_omni",
    "phi4mm",
    "qwen3_omni_moe",
];

/// `mlx_vlm.speculative.drafters.DRAFTER_KIND_BY_MODEL_TYPE`.
pub const MLX_VLM_DRAFTER_KIND_BY_MODEL_TYPE: &[(&str, &str)] = &[
    ("deepseek_v4_mtp", "mtp"),
    ("deepseek_v4_dspark", "dflash"),
    ("dspark", "dflash"),
    ("gemma4_dspark", "dflash"),
    ("eagle3", "eagle3"),
    ("gemma4_assistant", "mtp"),
    ("gemma4_unified_assistant", "mtp"),
    ("glm4_moe_lite_mtp", "mtp"),
    ("glm5_next_mtp", "mtp"),
    ("glm_moe_dsa_mtp", "mtp"),
    ("hy_v4_mtp", "mtp"),
    ("inkling_mtp", "mtp"),
    ("qwen3_5_mtp", "mtp"),
    ("qwen4_exp_mtp", "mtp"),
    ("laguna", "dflash"),
    ("muse_glimmer_assistant", "dflash"),
    ("qwen3_dspark", "dflash"),
];
