import type { Locale } from '../../shared/i18n/i18n';

const en = {
  welcome: 'Welcome to AioLM',
  intro: 'A few choices to make this space yours.',
  steps: ['Language', 'Appearance', 'Model folder'],
  progress: 'Setup progress',
  titles: ['Choose your language', 'Make yourself at home', 'Give your models a home'],
  descriptions: [
    'Choose the language you want to use in AioLM.',
    'Pick a theme. You can see the change right away.',
    'Choose where AioLM finds your local models and saves new downloads.',
  ],
  later: 'You can change these choices later in Settings and the model library.',
  next: 'Continue', back: 'Back', finish: 'Start using AioLM', saving: 'Saving…',
  browse: 'Choose folder', choosing: 'Opening…', defaultFolder: 'Use default folder',
  folderLabel: 'Models folder', folderHint: 'Use the default folder or choose one that already contains GGUF models. You can download your first model later.',
  noModels: 'No model needed yet', noModelsHint: 'Your workspace will be ready when you are. Choosing a folder does not move or delete any files.',
  saveError: 'Could not save setup. Your choices are still here. Please try again.',
  folderError: 'Could not open the folder picker. Please try again.',
  folderRequired: 'Choose a models folder to continue.',
  systemHint: 'Follow your device', lightHint: 'Bright and clear', darkHint: 'Easy on the eyes',
};

type SetupCopy = { [K in keyof typeof en]: typeof en[K] };
export const onboardingCopy: Record<Locale, SetupCopy> = {
  en,
  ko: {
    welcome: 'AioLM에 오신 것을 환영합니다', intro: '몇 가지 설정으로 나만의 작업 공간을 준비하세요.',
    steps: ['언어', '테마', '모델 폴더'], progress: '초기 설정 진행',
    titles: ['언어를 선택하세요', '편안한 테마를 선택하세요', '모델을 보관할 폴더를 선택하세요'],
    descriptions: ['AioLM에서 사용할 언어를 선택하세요.', '테마를 선택하면 화면에 바로 적용됩니다.', '로컬 모델을 찾고 새로 다운로드한 모델을 저장할 위치를 선택하세요.'],
    later: '나중에 설정과 모델 라이브러리에서 변경할 수 있습니다.',
    next: '계속', back: '이전', finish: 'AioLM 시작하기', saving: '저장 중…',
    browse: '폴더 선택', choosing: '여는 중…', defaultFolder: '기본 폴더 사용',
    folderLabel: '모델 폴더', folderHint: '기본 폴더를 사용하거나 GGUF 모델이 있는 폴더를 선택하세요. 첫 모델은 나중에 다운로드해도 됩니다.',
    noModels: '아직 모델이 없어도 괜찮아요', noModelsHint: '준비가 되면 모델을 추가하세요. 폴더를 선택해도 기존 파일을 이동하거나 삭제하지 않습니다.',
    saveError: '설정을 저장하지 못했습니다. 선택한 내용은 유지됩니다. 다시 시도해 주세요.',
    folderError: '폴더 선택 창을 열지 못했습니다. 다시 시도해 주세요.', folderRequired: '계속하려면 모델 폴더를 선택하세요.',
    systemHint: '기기 설정에 맞춰', lightHint: '밝고 선명하게', darkHint: '눈이 편안하게',
  },
  ja: {
    welcome: 'AioLMへようこそ', intro: 'いくつかの設定で、自分だけのワークスペースに。',
    steps: ['言語', 'テーマ', 'モデルフォルダー'], progress: '初期設定の進行状況',
    titles: ['言語を選択', 'テーマを選択', 'モデルの保存先を選択'],
    descriptions: ['AioLMで使用する言語を選択してください。', 'テーマを選ぶと、すぐに画面に反映されます。', 'ローカルモデルの検索先と、新しいモデルのダウンロード先を選択してください。'],
    later: 'あとで設定とモデルライブラリから変更できます。',
    next: '次へ', back: '戻る', finish: 'AioLMを始める', saving: '保存中…',
    browse: 'フォルダーを選択', choosing: '開いています…', defaultFolder: '既定のフォルダーを使用',
    folderLabel: 'モデルフォルダー', folderHint: '既定のフォルダー、またはGGUFモデルがあるフォルダーを選択してください。モデルはあとでダウンロードできます。',
    noModels: 'モデルはあとから追加できます', noModelsHint: '準備ができたらモデルを追加しましょう。フォルダーを選択しても、既存のファイルは移動・削除されません。',
    saveError: '設定を保存できませんでした。選択内容は保持されています。再試行してください。',
    folderError: 'フォルダー選択を開けませんでした。再試行してください。', folderRequired: 'モデルフォルダーを選択してください。',
    systemHint: 'デバイスに合わせる', lightHint: '明るく鮮明に', darkHint: '目にやさしく',
  },
  zh: {
    welcome: '欢迎使用 AioLM', intro: '只需几项设置，即可打造你的工作空间。',
    steps: ['语言', '主题', '模型文件夹'], progress: '初始设置进度',
    titles: ['选择语言', '选择喜欢的主题', '选择模型存储位置'],
    descriptions: ['选择你在 AioLM 中使用的语言。', '选择主题，即刻预览效果。', '选择查找本地模型和保存新下载模型的位置。'],
    later: '以后可以在设置和模型库中更改这些选项。',
    next: '继续', back: '上一步', finish: '开始使用 AioLM', saving: '正在保存…',
    browse: '选择文件夹', choosing: '正在打开…', defaultFolder: '使用默认文件夹',
    folderLabel: '模型文件夹', folderHint: '使用默认文件夹，或选择已有 GGUF 模型的文件夹。你可以稍后下载第一个模型。',
    noModels: '暂时没有模型也没关系', noModelsHint: '准备好后再添加模型。选择文件夹不会移动或删除任何现有文件。',
    saveError: '无法保存设置。你的选择已保留，请重试。',
    folderError: '无法打开文件夹选择窗口，请重试。', folderRequired: '请选择模型文件夹以继续。',
    systemHint: '跟随设备设置', lightHint: '明亮清晰', darkHint: '舒适护眼',
  },
};
