export const updateText = {
  en: {
    title: "Application updates", description: "Check for a new AioLM version and install updates.",
    current: "Current version", latest: "Latest version", check: "Check for updates", checking: "Checking for updates…",
    idle: "Updates are checked automatically when the app starts.", upToDate: "AioLM is up to date.", noRelease: "No published release is available yet.",
    available: "A new AioLM version is available", open: "View update", install: "Download and install",
    downloading: "Downloading update…", verifying: "Verifying download…", installing: "Opening installer…", started: "Installer opened. Follow its instructions to finish updating.",
    checkFailed: "Could not check for updates.", installFailed: "Could not install the update.",
    nativeOnly: "Update checks are available in the desktop app.", unsupported: "In-app installation is unavailable for this installation or platform. Use the release installer to update manually.",
    confirmTitle: "Install AioLM update?", confirmBody: "After the download is verified, AioLM will close and the installer will open. Running chats, servers and tasks will stop. Save your work before continuing. Follow the installer instructions, then reopen AioLM.",
    notes: "Release notes", downloadProgress: "Update download progress", releasePage: "Open release page",
  },
  ko: {
    title: "앱 업데이트", description: "새로운 AioLM 버전을 확인하고 업데이트를 설치합니다.",
    current: "현재 버전", latest: "최신 버전", check: "업데이트 확인", checking: "업데이트 확인 중…",
    idle: "앱을 시작할 때 자동으로 업데이트를 확인합니다.", upToDate: "최신 버전의 AioLM을 사용하고 있습니다.", noRelease: "아직 게시된 릴리스가 없습니다.",
    available: "새로운 AioLM 버전이 있습니다", open: "업데이트 보기", install: "다운로드 및 설치",
    downloading: "업데이트 다운로드 중…", verifying: "다운로드 검증 중…", installing: "설치 프로그램 여는 중…", started: "설치 프로그램을 열었습니다. 안내에 따라 업데이트를 완료하세요.",
    checkFailed: "업데이트를 확인하지 못했습니다.", installFailed: "업데이트를 설치하지 못했습니다.",
    nativeOnly: "데스크톱 앱에서 업데이트를 확인할 수 있습니다.", unsupported: "현재 설치 방식 또는 운영체제에서는 앱 내 설치를 지원하지 않습니다. 릴리스의 설치 파일로 직접 업데이트하세요.",
    confirmTitle: "AioLM을 업데이트할까요?", confirmBody: "다운로드 검증이 끝나면 AioLM이 종료되고 설치 프로그램이 열립니다. 실행 중인 대화, 서버 및 작업이 중단됩니다. 계속하기 전에 작업을 저장하세요. 설치 안내를 따른 뒤 AioLM을 다시 실행하세요.",
    notes: "릴리스 노트", downloadProgress: "업데이트 다운로드 진행률", releasePage: "릴리스 페이지 열기",
  },
  ja: {
    title: "アプリの更新", description: "AioLMの新しいバージョンを確認し、更新をインストールします。",
    current: "現在のバージョン", latest: "最新バージョン", check: "更新を確認", checking: "更新を確認中…",
    idle: "アプリの起動時に自動的に更新を確認します。", upToDate: "AioLMは最新です。", noRelease: "公開済みのリリースはまだありません。",
    available: "新しいAioLMバージョンがあります", open: "更新を表示", install: "ダウンロードしてインストール",
    downloading: "更新をダウンロード中…", verifying: "ダウンロードを検証中…", installing: "インストーラーを起動中…", started: "インストーラーを起動しました。案内に従って更新を完了してください。",
    checkFailed: "更新を確認できませんでした。", installFailed: "更新をインストールできませんでした。",
    nativeOnly: "デスクトップアプリで更新を確認できます。", unsupported: "現在のインストール方法または環境ではアプリ内の更新に対応していません。リリースのインストーラーで手動更新してください。",
    confirmTitle: "AioLMを更新しますか？", confirmBody: "ダウンロードの検証後、AioLMが終了し、インストーラーが開きます。実行中のチャット、サーバー、タスクは停止します。作業を保存してから続行してください。インストール後、AioLMを再起動してください。",
    notes: "リリースノート", downloadProgress: "更新ダウンロードの進行状況", releasePage: "リリースページを開く",
  },
  zh: {
    title: "应用更新", description: "检查AioLM的新版本并安装更新。",
    current: "当前版本", latest: "最新版本", check: "检查更新", checking: "正在检查更新…",
    idle: "应用启动时会自动检查更新。", upToDate: "AioLM已是最新版本。", noRelease: "尚无已发布的版本。",
    available: "有新的AioLM版本可用", open: "查看更新", install: "下载并安装",
    downloading: "正在下载更新…", verifying: "正在验证下载…", installing: "正在打开安装程序…", started: "安装程序已打开，请按照提示完成更新。",
    checkFailed: "无法检查更新。", installFailed: "无法安装更新。",
    nativeOnly: "请在桌面应用中检查更新。", unsupported: "当前安装方式或系统不支持应用内安装。请使用发布页面的安装程序手动更新。",
    confirmTitle: "更新AioLM？", confirmBody: "下载验证完成后，AioLM将关闭并打开安装程序。正在运行的对话、服务器和任务将停止。请先保存工作。按照安装提示完成后，重新打开AioLM。",
    notes: "发行说明", downloadProgress: "更新下载进度", releasePage: "打开发行页面",
  },
};
