import type { Locale } from "../../shared/i18n/i18n";
import { inferenceMetricCopy } from "../../shared/i18n/inferenceMetricCopy.ts";
import { benchmarkSharingCopy } from './benchmarkSharingCopy';

const en = {
  title: "Benchmark", description: "Compare response speed across prompt lengths and concurrent requests.",
  conditions: "Test conditions", model: "Selected model", corpus: "Prompt content", promptLengths: "Input tokens", generation: "Output tokens", repetitions: "Repetitions", batchSizes: "Concurrent requests", warmup: "Warm up before measuring",
  batchHint: "Every selected input length includes a single request as the comparison baseline.",
  workloadNote: "Server context length and request slots are set from these conditions.",
  code_python: "Code · Python", code_mixed: "Code · Mixed", novel_ko: "Prose · Korean", novel_en: "Prose · English", novel_ja: "Prose · Japanese",
  run: "Run benchmark", cancel: "Cancel benchmark", cancelling: "Cancelling…", stopServer: "Unload model", stopHint: "Unload the model before benchmarking. A dedicated server measures the selected model. The API keeps running.", noModel: "Select a model from Models to get started.",
  totalTests: "Total trials", idle: "Ready to benchmark", starting: "Preparing model…", complete: "Completed", cancelled: "Cancelled", failed: "Failed", partial: "Partial results",
  single: "Single requests", batch: "Concurrent requests", test: "Input / output tokens", repeat: "Samples", ttft: "TTFT", tpot: "TPOT", pp: inferenceMetricCopy("en").prefillEstimated, tg: inferenceMetricCopy("en").decode, e2e: "Total time", throughput: "Total throughput", memory: "Peak process RAM", speedup: "Speedup", unavailable: "N/A",
  emptyTitle: "No results yet",
  empty: "Choose the test conditions and run a benchmark. Results appear here as each test finishes.",
  history: "Result history", current: "Current run", exportFile: "Export result", exportFormat: "Export format", copy: "Copy Markdown", copied: "Copied", metrics: "About these metrics",
  exportSaved: "File saved.", exportStarted: "Download started.", exportError: "Could not export the file.",
  deleteHistory: "Delete result", deleteTitle: "Delete this result?", deleteHint: "Permanently remove the selected result from local history. Results shared on the website and their management access are kept.",
  deleting: "Deleting…", deleteSuccess: "Result deleted.", deleteError: "Could not delete the result. Try again.",
  metricsHint: `Rates use client-observed timings. Repeated tests show means and ${inferenceMetricCopy("en").decode} speed standard deviation.`,
  ttftHint: "Average wait until the first token.",
  tpotHint: "Average time per output token after the first token.",
  ppHint: "Total input tokens divided by the time until every request receives its first token. Includes queueing and transfer time.",
  tgHint: "Output tokens, excluding each request’s first token, divided by the time from the first output to the last output.",
  throughputHint: `Output tokens divided by the full elapsed time, including ${inferenceMetricCopy("en").prefill}.`,
  memoryHint: "Sampled peak process RAM, not GPU VRAM. Unavailable measurements remain N/A.",
  speedupHint: `${inferenceMetricCopy("en").decode} rate divided by the single-request rate with the same input/output token counts and timing method.`,
  storageError: "The result could not be saved to history. It remains on this screen and can be exported to a file.",
  validation: "Select at least one input length. Output tokens must be 1–4,096 and repetitions 1–10.",
  activeElsewhere: "Another benchmark is running. Wait for it to finish before starting a new run.",
  details: "Run configuration", seconds: "s", milliseconds: "ms", tokens: "tok/s", processor: "Processor", systemMemory: "System memory",
  running: "Measuring…", cleanup: "Finishing benchmark…", measuringSingle: "Measuring single requests…", measuringBatch: "Measuring concurrent requests…",
  exportAllCsv: "Export all history", contextSize: "Server context tokens", parallel: "Server request slots", runtimeVersion: "Runtime version", enabled: "Enabled", disabled: "Disabled",
  effectiveArgs: "Effective llama-server arguments",
} as const;

type BenchmarkCopy = { [K in keyof typeof en]: string };

const ko: BenchmarkCopy = {
  title: "벤치마크", description: "입력 길이와 동시 요청 수에 따른 응답 속도를 비교합니다.",
  conditions: "측정 조건", model: "선택한 모델", corpus: "입력 내용", promptLengths: "입력 토큰 수", generation: "출력 토큰 수", repetitions: "반복 횟수", batchSizes: "동시 요청 수", warmup: "측정 전 워밍업",
  batchHint: "선택한 모든 입력 길이에서 단일 요청을 함께 측정해 비교 기준으로 사용합니다.",
  workloadNote: "서버 컨텍스트 길이와 요청 슬롯은 이 측정 조건으로 정해집니다.",
  code_python: "코드 · Python", code_mixed: "코드 · 혼합", novel_ko: "산문 · 한국어", novel_en: "산문 · 영어", novel_ja: "산문 · 일본어",
  run: "벤치마크 실행", cancel: "벤치마크 취소", cancelling: "취소 중…", stopServer: "모델 언로드", stopHint: "벤치마크를 실행하려면 모델을 언로드하세요. 전용 서버로 선택한 모델을 측정하며 API는 계속 실행됩니다.", noModel: "모델 화면에서 측정할 모델을 선택하세요.",
  totalTests: "전체 측정 횟수", idle: "측정 준비 완료", starting: "모델 준비 중…", complete: "완료", cancelled: "취소됨", failed: "실패", partial: "부분 결과",
  single: "단일 요청", batch: "동시 요청", test: "입력 / 출력 토큰", repeat: "표본 수", ttft: "TTFT", tpot: "TPOT", pp: inferenceMetricCopy("ko").prefillEstimated, tg: inferenceMetricCopy("ko").decode, e2e: "전체 시간", throughput: "전체 처리량", memory: "최대 프로세스 RAM", speedup: "속도 배율", unavailable: "측정 불가",
  emptyTitle: "아직 결과가 없습니다",
  empty: "측정 조건을 선택하고 벤치마크를 실행하세요. 각 측정이 끝나면 결과가 표시됩니다.",
  history: "결과 이력", current: "현재 실행", exportFile: "결과 내보내기", exportFormat: "내보내기 형식", copy: "Markdown으로 복사", copied: "복사됨", metrics: "측정 지표 안내",
  exportSaved: "파일을 저장했습니다.", exportStarted: "다운로드를 시작했습니다.", exportError: "파일을 내보내지 못했습니다.",
  deleteHistory: "이력 삭제", deleteTitle: "이 결과 이력을 삭제할까요?", deleteHint: "선택한 결과를 이 기기의 이력에서 삭제합니다. 이 작업은 되돌릴 수 없습니다. 웹사이트에 공유한 결과와 관리 권한은 유지됩니다.",
  deleting: "삭제 중…", deleteSuccess: "결과 이력을 삭제했습니다.", deleteError: "결과 이력을 삭제하지 못했습니다. 다시 시도해 주세요.",
  metricsHint: `속도는 클라이언트에서 관측한 시간으로 계산합니다. 반복 측정은 평균과 ${inferenceMetricCopy("ko").decode} 속도의 표준편차를 표시합니다.`,
  ttftHint: "첫 토큰까지의 평균 대기 시간입니다.",
  tpotHint: "첫 토큰 이후 출력 토큰 하나당 평균 시간입니다.",
  ppHint: "총 입력 토큰을 모든 요청의 첫 토큰이 도착할 때까지의 시간으로 나눈 추정값입니다. 대기와 전송 시간이 포함됩니다.",
  tgHint: "각 요청의 첫 토큰을 제외한 출력 토큰 수를 첫 출력부터 마지막 출력까지의 시간으로 나눈 값입니다.",
  throughputHint: `출력 토큰 수를 ${inferenceMetricCopy("ko").prefill}를 포함한 전체 소요 시간으로 나눈 값입니다.`,
  memoryHint: "샘플링한 프로세스 최대 RAM이며 GPU VRAM이 아닙니다. 확인할 수 없는 값은 측정 불가로 표시합니다.",
  speedupHint: `입력·출력 토큰 수와 측정 방식이 같은 단일 요청 대비 ${inferenceMetricCopy("ko").decode} 속도의 배율입니다.`,
  storageError: "결과 이력에 저장하지 못했습니다. 현재 화면에서 결과를 확인하고 파일로 내보낼 수 있습니다.",
  validation: "입력 길이를 하나 이상 선택하세요. 출력 토큰은 1~4,096, 반복 횟수는 1~10이어야 합니다.",
  activeElsewhere: "다른 벤치마크가 실행 중입니다. 완료 후 새 측정을 시작하세요.",
  details: "실행 설정", seconds: "s", milliseconds: "ms", tokens: "tok/s", processor: "프로세서", systemMemory: "시스템 메모리",
  running: "측정 중…", cleanup: "벤치마크 마무리 중…", measuringSingle: "단일 요청 측정 중…", measuringBatch: "동시 요청 측정 중…",
  exportAllCsv: "전체 이력 내보내기", contextSize: "서버 컨텍스트 토큰", parallel: "서버 요청 슬롯", runtimeVersion: "런타임 버전", enabled: "사용", disabled: "사용 안 함",
  effectiveArgs: "실제 llama-server 인자",
};

const ja: BenchmarkCopy = {
  title: "ベンチマーク", description: "入力長と同時リクエスト数による応答速度を比較します。",
  conditions: "測定条件", model: "選択中のモデル", corpus: "入力内容", promptLengths: "入力トークン数", generation: "出力トークン数", repetitions: "繰り返し回数", batchSizes: "同時リクエスト数", warmup: "測定前にウォームアップ",
  batchHint: "選択した各入力長で単一リクエストも測定し、比較の基準にします。",
  workloadNote: "サーバーのコンテキスト長とリクエスト枠は、これらの測定条件で決まります。",
  code_python: "コード · Python", code_mixed: "コード · 混合", novel_ko: "散文 · 韓国語", novel_en: "散文 · 英語", novel_ja: "散文 · 日本語",
  run: "ベンチマークを実行", cancel: "ベンチマークを中止", cancelling: "中止中…", stopServer: "モデルをアンロード", stopHint: "測定前にモデルをアンロードしてください。専用サーバーで選択したモデルを測定します。APIは動作し続けます。", noModel: "モデル画面から測定するモデルを選択してください。",
  totalTests: "総測定回数", idle: "測定準備完了", starting: "モデル準備中…", complete: "完了", cancelled: "中止済み", failed: "失敗", partial: "部分的な結果",
  single: "単一リクエスト", batch: "同時リクエスト", test: "入力 / 出力トークン", repeat: "サンプル数", ttft: "TTFT", tpot: "TPOT", pp: inferenceMetricCopy("ja").prefillEstimated, tg: inferenceMetricCopy("ja").decode, e2e: "合計時間", throughput: "総処理量", memory: "最大プロセスRAM", speedup: "速度倍率", unavailable: "測定不可",
  emptyTitle: "まだ結果がありません",
  empty: "条件を選択してベンチマークを実行してください。各測定が完了すると結果が表示されます。",
  history: "結果履歴", current: "現在の実行", exportFile: "結果を書き出す", exportFormat: "書き出し形式", copy: "Markdownでコピー", copied: "コピー済み", metrics: "測定指標について",
  exportSaved: "ファイルを保存しました。", exportStarted: "ダウンロードを開始しました。", exportError: "ファイルを書き出せませんでした。",
  deleteHistory: "結果を削除", deleteTitle: "この結果を削除しますか？", deleteHint: "選択した結果をローカル履歴から削除します。この操作は元に戻せません。ウェブサイトで共有した結果と管理権限は保持されます。",
  deleting: "削除中…", deleteSuccess: "結果を削除しました。", deleteError: "結果を削除できませんでした。もう一度お試しください。",
  metricsHint: `速度はクライアントで観測した時間から計算します。繰り返し測定は平均と${inferenceMetricCopy("ja").decode}速度の標準偏差を表示します。`,
  ttftHint: "最初のトークンまでの平均待機時間です。",
  tpotHint: "最初のトークン以降の出力トークンあたりの平均時間です。",
  ppHint: "合計入力トークンを、全リクエストの最初のトークンが到着するまでの時間で割った推定値です。待機・転送時間も含みます。",
  tgHint: "各リクエストの最初のトークンを除く出力トークン数を、最初から最後の出力までの時間で割った値です。",
  throughputHint: `出力トークン数を、${inferenceMetricCopy("ja").prefill}も含む合計時間で割った値です。`,
  memoryHint: "サンプリングしたプロセスの最大RAMです。GPU VRAMではありません。取得できない値は測定不可です。",
  speedupHint: `入出力トークン数と測定方式が同じ単一リクエストに対する${inferenceMetricCopy("ja").decode}速度の倍率です。`,
  storageError: "結果を履歴に保存できませんでした。この画面で確認し、ファイルに書き出せます。",
  validation: "入力長を1つ以上選択してください。出力トークンは1〜4,096、繰り返しは1〜10です。",
  activeElsewhere: "別のベンチマークが実行中です。完了後に開始してください。",
  details: "実行設定", seconds: "s", milliseconds: "ms", tokens: "tok/s", processor: "プロセッサ", systemMemory: "システムメモリ",
  running: "測定中…", cleanup: "ベンチマークを終了中…", measuringSingle: "単一リクエストを測定中…", measuringBatch: "同時リクエストを測定中…",
  exportAllCsv: "すべての履歴を書き出す", contextSize: "サーバーのコンテキストトークン", parallel: "サーバーのリクエスト枠", runtimeVersion: "ランタイムバージョン", enabled: "有効", disabled: "無効",
  effectiveArgs: "実際の llama-server 引数",
};

const zh: BenchmarkCopy = {
  title: "基准测试", description: "比较不同输入长度和并发请求数下的响应速度。",
  conditions: "测试条件", model: "已选模型", corpus: "输入内容", promptLengths: "输入令牌数", generation: "输出令牌数", repetitions: "重复次数", batchSizes: "并发请求数", warmup: "测量前预热",
  batchHint: "每个选定的输入长度都会测量单个请求，作为比较基准。",
  workloadNote: "服务器上下文长度和请求槽位由这些测试条件决定。",
  code_python: "代码 · Python", code_mixed: "代码 · 混合", novel_ko: "散文 · 韩语", novel_en: "散文 · 英语", novel_ja: "散文 · 日语",
  run: "运行基准测试", cancel: "取消基准测试", cancelling: "正在取消…", stopServer: "卸载模型", stopHint: "请先卸载模型，再运行基准测试。专用服务器将测量所选模型，API 会继续运行。", noModel: "请在模型页面选择要测试的模型。",
  totalTests: "总测量次数", idle: "准备就绪", starting: "正在准备模型…", complete: "已完成", cancelled: "已取消", failed: "失败", partial: "部分结果",
  single: "单个请求", batch: "并发请求", test: "输入 / 输出令牌", repeat: "样本数", ttft: "TTFT", tpot: "TPOT", pp: inferenceMetricCopy("zh").prefillEstimated, tg: inferenceMetricCopy("zh").decode, e2e: "总耗时", throughput: "总吞吐量", memory: "进程峰值 RAM", speedup: "加速比", unavailable: "不可测量",
  emptyTitle: "暂无结果",
  empty: "选择条件并运行基准测试。每项测试完成后会显示结果。",
  history: "结果历史", current: "当前运行", exportFile: "导出结果", exportFormat: "导出格式", copy: "复制 Markdown", copied: "已复制", metrics: "测量指标说明",
  exportSaved: "已保存文件。", exportStarted: "已开始下载。", exportError: "无法导出文件。",
  deleteHistory: "删除结果", deleteTitle: "删除此结果？", deleteHint: "将从本地历史记录中删除所选结果，此操作无法撤销。网站上已分享的结果及其管理权限会保留。",
  deleting: "正在删除…", deleteSuccess: "已删除结果。", deleteError: "无法删除结果。请重试。",
  metricsHint: `速度使用客户端观测时间计算。重复测量显示平均值和${inferenceMetricCopy("zh").decode}速度的标准差。`,
  ttftHint: "首个令牌的平均等待时间。",
  tpotHint: "首个令牌之后，每个输出令牌的平均耗时。",
  ppHint: "总输入令牌除以所有请求收到首个令牌所需的时间，包含等待和传输时间。",
  tgHint: "不含各请求首个令牌的输出令牌数，除以从首次输出到最后输出的耗时。",
  throughputHint: `输出令牌数除以包括${inferenceMetricCopy("zh").prefill}在内的总耗时。`,
  memoryHint: "采样得到的进程峰值 RAM，并非 GPU 显存。无法获取的数值显示为不可测量。",
  speedupHint: `${inferenceMetricCopy("zh").decode}速度与相同输入输出令牌数和计时方式的单个请求速度之比。`,
  storageError: "无法将结果保存到历史记录。您仍可在当前页面查看并导出文件。",
  validation: "请至少选择一个输入长度。输出令牌范围为 1–4,096，重复次数为 1–10。",
  activeElsewhere: "另一项基准测试正在运行。请等待完成后再开始。",
  details: "运行配置", seconds: "s", milliseconds: "ms", tokens: "tok/s", processor: "处理器", systemMemory: "系统内存",
  running: "正在测量…", cleanup: "正在结束基准测试…", measuringSingle: "正在测量单个请求…", measuringBatch: "正在测量并发请求…",
  exportAllCsv: "导出全部历史", contextSize: "服务器上下文令牌", parallel: "服务器请求槽位", runtimeVersion: "运行时版本", enabled: "启用", disabled: "禁用",
  effectiveArgs: "实际 llama-server 参数",
};

const copies: Record<Locale, BenchmarkCopy> = { en, ko, ja, zh };
export const benchmarkCopy = (locale: Locale) => ({ ...copies[locale], concurrency: copies[locale].batchSizes, ...benchmarkSharingCopy(locale) });
