import type { Locale } from '../../shared/i18n/i18n';

const en = {
  publicReview: 'Public sharing', publicHint: 'Review the hardware, workload and measurements to include in a public result. Local model paths, command arguments, diagnostic messages and device identifiers are excluded.',
  preparePublic: 'Review public result', publicPreview: 'Public result preview', exportPublic: 'Export public JSON',
  publicUnknown: 'Unknown provenance remains unknown. Older runs cannot establish the model hash or the devices used during measurement.',
  publicInvalid: 'This record cannot be converted to the public format. The original result remains available for local export.',
  queuePublic: 'Save to sharing queue', queued: 'Saved to sharing queue', queueHint: 'The reviewed result is saved on this device. Upload will be available when a sharing service is connected.',
  queueError: 'The sharing queue could not be saved. Export the public JSON to keep this snapshot.',
  hydrateLoading: 'Loading saved snapshot…',
  hydrateError: 'The saved sharing snapshot could not be read. Export and publishing are disabled so a different result cannot be sent.',
  sharingQueue: 'Sharing queue', queueReadError: 'The sharing queue is unavailable. Existing submissions are retained.', queuePending: 'Pending upload', queueSent: 'Uploaded', queueRejected: 'Upload rejected', removeQueued: 'Remove from queue',
  historyError: 'History could not be loaded or migrated. Existing records are retained.', historyWarning: 'Some records could not be read or updated. Available results are shown and affected local records are retained.', historyLoading: 'Loading history…', loadMore: 'Load older results',
  identifyModel: 'Identify model for comparison', identifying: 'Identifying model…', identityHint: 'Optional: compute the model content hash before measuring. Large models can take time.',
  identityReady: 'Model identity is ready for the next run.', identityUnknown: 'Model identity or device selection is incomplete.', identifyError: 'The model could not be identified. You can still measure with an unknown identity.',
  executionDevice: 'Devices selected for this run', modelHash: 'Model SHA-256',
  localHistoryHint: 'Uploaded results are managed on the website. This device keeps recovery data and recent acknowledged copies. Existing and unuploaded records are retained.',
  localRecovery: 'Stored on this device', localCached: 'Saved on the website · local copy',
  queueLocalMaintenance: 'Uploaded · local maintenance pending', queueRemoveHint: 'Removing an item here does not delete a result saved on the website.',
  descriptionLabel: 'Public description (Markdown)', descriptionHint: 'Paragraphs, lists, http(s) links, and code blocks only. Max 4000 characters. No HTML, images, or executable links.',
  descriptionCount: 'Description length', previewDescription: 'Preview description',
  publishTitle: 'Anonymous publish', publishHint: 'One Publish action prepares the frozen result, verifies in the browser, and submits it. Save the recovery backup after publishing.',
  publishSelected: 'Publish selected result', cancelPublish: 'Cancel publish', reverify: 'Verify again',
  publishPreparing: 'Preparing…', publishSubmitting: 'Submitting…',
  publishNeedsService: 'No sharing service is configured. Review, export, and queue still work offline.',
  publishBlocked: 'Complete browser verification to publish.',
  publishDeleted: 'This result was deleted on the website and will not be retried.',
  publishError: 'Publishing failed. Check the status and try again.',
  publishAccepted: 'Upload accepted. Local receipt:',
  legacyConflict: 'This entry was already shared in the previous format and cannot take a description. Review and queue it again to publish with notes.',
  recoveryTitle: 'Owner recovery', recoveryHint: 'Save the recovery code after publishing. It restores management access; losing both key and backup cannot recover automatically.',
  recoveryExport: 'Save recovery file', recoveryImport: 'Import recovery file', recoveryCopy: 'Copy recovery code', openManagement: 'Open management page',
  recoverySaved: 'Recovery file saved.', recoveryImported: 'Recovery file imported.', recoveryCopied: 'Recovery code copied.',
  recoveryError: 'Recovery failed. Check the file and service, then try again.',
  queuePublish: 'Publish', queueRetry: 'Retry', queueCancel: 'Cancel',
  ownedListTitle: 'Saved ownership', ownedListHint: 'Device keys kept outside the sharing queue. Older results stay manageable after queue cleanup.',
  ownedListEmpty: 'No saved ownership yet.', ownedListLoadMore: 'Load more ownership',
};
type Copy = { [K in keyof typeof en]: string };
const ko: Copy = {
  publicReview: '공개 공유', publicHint: '공개 결과에 포함할 하드웨어, 측정 조건과 결과를 확인하세요. 로컬 모델 경로, 실행 인자, 진단 메시지와 장치 식별자는 제외됩니다.',
  preparePublic: '공개 결과 검토', publicPreview: '공개 결과 미리보기', exportPublic: '공개 JSON 내보내기',
  publicUnknown: '확인하지 못한 정보는 알 수 없음으로 유지됩니다. 이전 기록의 모델 해시나 측정 당시 사용 장치를 추정하지 않습니다.',
  publicInvalid: '이 기록은 공개 형식으로 변환할 수 없습니다. 원본 결과는 로컬 파일로 내보낼 수 있습니다.',
  queuePublic: '공유 대기열에 저장', queued: '공유 대기열에 저장됨', queueHint: '검토한 결과를 이 기기에 저장합니다. 공유 서비스가 연결되면 업로드할 수 있습니다.',
  queueError: '공유 대기열에 저장하지 못했습니다. 공개 JSON을 내보내 결과를 보관하세요.',
  hydrateLoading: '저장된 스냅샷을 불러오는 중…',
  hydrateError: '저장된 공유 스냅샷을 읽지 못했습니다. 다른 결과가 전송되지 않도록 내보내기와 게시를 비활성화했습니다.',
  sharingQueue: '공유 대기열', queueReadError: '공유 대기열을 사용할 수 없습니다. 기존 공유 기록은 유지됩니다.', queuePending: '업로드 대기', queueSent: '업로드 완료', queueRejected: '업로드 거부됨', removeQueued: '대기열에서 제거',
  historyError: '이력을 불러오거나 이전하지 못했습니다. 기존 기록은 유지됩니다.', historyWarning: '일부 기록을 읽거나 갱신하지 못했습니다. 확인 가능한 결과를 표시하며 해당 로컬 기록은 유지됩니다.', historyLoading: '이력 불러오는 중…', loadMore: '이전 결과 더 보기',
  identifyModel: '비교용 모델 식별', identifying: '모델 식별 중…', identityHint: '선택 사항: 측정 전에 모델 내용 해시를 계산합니다. 큰 모델은 시간이 걸릴 수 있습니다.',
  identityReady: '다음 측정에 사용할 모델 식별 정보가 준비되었습니다.', identityUnknown: '모델 식별 또는 사용 장치 정보가 완전하지 않습니다.', identifyError: '모델을 식별하지 못했습니다. 식별 정보 없이도 측정할 수 있습니다.',
  executionDevice: '이 측정에 선택한 장치', modelHash: '모델 SHA-256',
  localHistoryHint: '업로드한 결과는 웹사이트에서 관리합니다. 앱에는 복구용 데이터와 최근 서버 접수가 확인된 사본을 보관합니다. 기존 기록과 미전송 기록은 유지됩니다.',
  localRecovery: '이 기기에 보관 중', localCached: '웹사이트 저장 확인 · 로컬 사본',
  queueLocalMaintenance: '업로드 완료 · 기기 정리 대기', queueRemoveHint: '여기에서 제거해도 웹사이트에 저장된 결과는 삭제되지 않습니다.',
  descriptionLabel: '공개 설명 (Markdown)', descriptionHint: '문단, 목록, http(s) 링크, 코드 블록만 사용하세요. 최대 4000자. HTML, 이미지, 실행 링크는 사용할 수 없습니다.',
  descriptionCount: '설명 길이', previewDescription: '설명 미리보기',
  publishTitle: '익명 게시', publishHint: '게시 버튼 한 번으로 고정된 결과를 준비하고 브라우저에서 확인한 뒤 제출합니다. 게시 후 복구 백업을 저장하세요.',
  publishSelected: '선택 결과 게시', cancelPublish: '게시 취소', reverify: '다시 확인',
  publishPreparing: '준비 중…', publishSubmitting: '제출 중…',
  publishNeedsService: '공유 서비스가 설정되지 않았습니다. 검토, 내보내기, 대기열 저장은 오프라인에서도 동작합니다.',
  publishBlocked: '게시하려면 브라우저 확인을 완료하세요.',
  publishDeleted: '이 결과는 웹사이트에서 삭제되어 다시 시도하지 않습니다.',
  publishError: '게시하지 못했습니다. 상태를 확인하고 다시 시도하세요.',
  publishAccepted: '업로드가 접수되었습니다. 로컬 접수:',
  legacyConflict: '이 항목은 이전 형식으로 이미 공유되어 설명을 추가할 수 없습니다. 다시 검토·저장한 뒤 게시하세요.',
  recoveryTitle: '소유자 복구', recoveryHint: '게시 후 복구 코드를 저장하세요. 관리 접근을 복원합니다. 키와 백업을 모두 잃으면 자동 복구할 수 없습니다.',
  recoveryExport: '복구 파일 저장', recoveryImport: '복구 파일 가져오기', recoveryCopy: '복구 코드 복사', openManagement: '관리 페이지 열기',
  recoverySaved: '복구 파일을 저장했습니다.', recoveryImported: '복구 파일을 가져왔습니다.', recoveryCopied: '복구 코드를 복사했습니다.',
  recoveryError: '복구에 실패했습니다. 파일과 서비스를 확인하고 다시 시도하세요.',
  queuePublish: '게시', queueRetry: '다시 시도', queueCancel: '취소',
  ownedListTitle: '보관된 소유권', ownedListHint: '공유 대기열과 별도로 보관한 기기 키입니다. 대기열 정리 후에도 이전 결과를 관리할 수 있습니다.',
  ownedListEmpty: '보관된 소유권이 없습니다.', ownedListLoadMore: '소유권 더 보기',
};
const ja: Copy = {
  publicReview: '公開共有', publicHint: '公開するハードウェア、測定条件と結果を確認してください。ローカルパス、実行引数、診断メッセージ、デバイス識別子は含まれません。',
  preparePublic: '公開結果を確認', publicPreview: '公開結果のプレビュー', exportPublic: '公開JSONを書き出す',
  publicUnknown: '不明な情報は不明のまま保持します。過去の測定で使われたモデルハッシュやデバイスは推定しません。',
  publicInvalid: 'この記録を公開形式に変換できません。元の結果はローカルに書き出せます。',
  queuePublic: '共有キューに保存', queued: '共有キューに保存済み', queueHint: '確認した結果をこのデバイスに保存します。共有サービス接続後にアップロードできます。',
  queueError: '共有キューに保存できませんでした。公開JSONを書き出して保存してください。',
  hydrateLoading: '保存済みスナップショットを読み込み中…',
  hydrateError: '保存済みの共有スナップショットを読み込めませんでした。異なる結果を送信しないよう、書き出しと公開を無効にしました。',
  sharingQueue: '共有キュー', queueReadError: '共有キューを利用できません。既存の送信記録は保持されています。', queuePending: 'アップロード待ち', queueSent: 'アップロード済み', queueRejected: 'アップロード拒否', removeQueued: 'キューから削除',
  historyError: '履歴の読み込みまたは移行に失敗しました。既存の記録は保持されています。', historyWarning: '一部の記録を読み込みまたは更新できませんでした。利用できる結果を表示し、該当するローカル記録は保持しています。', historyLoading: '履歴を読み込み中…', loadMore: '以前の結果を読み込む',
  identifyModel: '比較用にモデルを識別', identifying: 'モデルを識別中…', identityHint: '任意：測定前にモデル内容のハッシュを計算します。大きなモデルは時間がかかる場合があります。',
  identityReady: '次の測定用にモデル識別情報を準備しました。', identityUnknown: 'モデル識別またはデバイス選択情報が不完全です。', identifyError: 'モデルを識別できませんでした。識別情報なしでも測定できます。',
  executionDevice: 'この測定で選択したデバイス', modelHash: 'モデルSHA-256',
  localHistoryHint: 'アップロードした結果はウェブサイトで管理します。このデバイスには復旧用データと、受理された最近のコピーを保持します。既存および未送信の記録は保持します。',
  localRecovery: 'このデバイスに保存', localCached: 'ウェブサイトに保存済み · ローカルコピー',
  queueLocalMaintenance: 'アップロード済み · ローカル整理待ち', queueRemoveHint: 'ここから削除してもウェブサイトの結果は削除されません。',
  descriptionLabel: '公開説明 (Markdown)', descriptionHint: '段落、リスト、http(s)リンク、コードブロックのみ。最大4000文字。HTML、画像、実行可能リンクは不可。',
  descriptionCount: '説明の長さ', previewDescription: '説明のプレビュー',
  publishTitle: '匿名公開', publishHint: '公開ボタン一度で結果を確定し、ブラウザで確認して送信します。公開後は復旧バックアップを保存してください。',
  publishSelected: '選択結果を公開', cancelPublish: '公開を中止', reverify: '再確認',
  publishPreparing: '準備中…', publishSubmitting: '送信中…',
  publishNeedsService: '共有サービスが未設定です。確認、書き出し、キュー保存はオフラインでも利用できます。',
  publishBlocked: '公開するにはブラウザ確認を完了してください。',
  publishDeleted: 'この結果はウェブサイトで削除され、再試行しません。',
  publishError: '公開に失敗しました。状態を確認して再試行してください。',
  publishAccepted: 'アップロードを受理しました。ローカル受付:',
  legacyConflict: 'この項目は旧形式で共有済みのため説明を追加できません。確認・保存し直してから公開してください。',
  recoveryTitle: '所有者の復旧', recoveryHint: '公開後に復旧コードを保存してください。管理アクセスを復元します。キーとバックアップの両方を失うと自動復旧できません。',
  recoveryExport: '復旧ファイルを保存', recoveryImport: '復旧ファイルを取り込む', recoveryCopy: '復旧コードをコピー', openManagement: '管理ページを開く',
  recoverySaved: '復旧ファイルを保存しました。', recoveryImported: '復旧ファイルを取り込みました。', recoveryCopied: '復旧コードをコピーしました。',
  recoveryError: '復旧に失敗しました。ファイルとサービスを確認してください。',
  queuePublish: '公開', queueRetry: '再試行', queueCancel: '中止',
  ownedListTitle: '保存済みの所有権', ownedListHint: '共有キューとは別に保管したデバイスキーです。キューの整理後も以前の結果を管理できます。',
  ownedListEmpty: '保存済みの所有権はありません。', ownedListLoadMore: '所有権をさらに読み込む',
};
const zh: Copy = {
  publicReview: '公开分享', publicHint: '查看将公开的硬件、测试条件和结果。不包含本地模型路径、运行参数、诊断消息或设备标识符。',
  preparePublic: '查看公开结果', publicPreview: '公开结果预览', exportPublic: '导出公开JSON',
  publicUnknown: '未知信息仍保留为未知。不会推断历史测试的模型哈希或所用设备。',
  publicInvalid: '无法将此记录转换为公开格式。原始结果仍可导出到本地。',
  queuePublic: '保存到分享队列', queued: '已保存到分享队列', queueHint: '已审核的结果会保存在此设备上。连接分享服务后即可上传。',
  queueError: '无法保存分享队列。请导出公开JSON以保留结果。',
  hydrateLoading: '正在加载已保存的快照…',
  hydrateError: '无法读取已保存的分享快照。已禁用导出和发布，以防发送不同的结果。',
  sharingQueue: '分享队列', queueReadError: '分享队列不可用。已有分享记录保持不变。', queuePending: '等待上传', queueSent: '已上传', queueRejected: '上传被拒绝', removeQueued: '从队列中移除',
  historyError: '无法加载或迁移历史记录。已有记录保持不变。', historyWarning: '部分记录无法读取或更新。显示可用的结果，相关本地记录保持不变。', historyLoading: '正在加载历史…', loadMore: '加载更早的结果',
  identifyModel: '识别模型以进行比较', identifying: '正在识别模型…', identityHint: '可选：在测试前计算模型内容哈希。较大的模型可能需要一些时间。',
  identityReady: '已为下次测试准备模型标识信息。', identityUnknown: '模型标识或设备选择信息不完整。', identifyError: '无法识别模型。仍可在标识未知的情况下进行测试。',
  executionDevice: '本次测试选择的设备', modelHash: '模型SHA-256',
  localHistoryHint: '已上传的结果由网站管理。此设备保留恢复数据和最近服务器已确认的副本。已有和未发送的记录会保留。',
  localRecovery: '保存在此设备', localCached: '网站已保存 · 本地副本',
  queueLocalMaintenance: '已上传 · 等待本地整理', queueRemoveHint: '从此处移除不会删除网站上保存的结果。',
  descriptionLabel: '公开说明 (Markdown)', descriptionHint: '仅支持段落、列表、http(s)链接和代码块。最多4000字符。不支持HTML、图片或可执行链接。',
  descriptionCount: '说明长度', previewDescription: '说明预览',
  publishTitle: '匿名发布', publishHint: '点一次发布即可固定结果、在浏览器中验证并提交。发布后请保存恢复备份。',
  publishSelected: '发布所选结果', cancelPublish: '取消发布', reverify: '重新验证',
  publishPreparing: '准备中…', publishSubmitting: '提交中…',
  publishNeedsService: '未配置分享服务。查看、导出和队列保存仍可离线使用。',
  publishBlocked: '请完成浏览器验证后再发布。',
  publishDeleted: '该结果已在网站删除，不会重试。',
  publishError: '发布失败。请检查状态后重试。',
  publishAccepted: '上传已受理。本地回执：',
  legacyConflict: '该条目已用旧格式分享，无法添加说明。请重新审核保存后再发布。',
  recoveryTitle: '所有者恢复', recoveryHint: '发布后请保存恢复码，用于恢复管理权限。同时丢失密钥和备份将无法自动恢复。',
  recoveryExport: '保存恢复文件', recoveryImport: '导入恢复文件', recoveryCopy: '复制恢复码', openManagement: '打开管理页面',
  recoverySaved: '已保存恢复文件。', recoveryImported: '已导入恢复文件。', recoveryCopied: '已复制恢复码。',
  recoveryError: '恢复失败。请检查文件和服务后重试。',
  queuePublish: '发布', queueRetry: '重试', queueCancel: '取消',
  ownedListTitle: '已保存的所有权', ownedListHint: '与分享队列分开保管的设备密钥。队列清理后仍可管理较早的结果。',
  ownedListEmpty: '暂无已保存的所有权。', ownedListLoadMore: '加载更多所有权',
};
const copies: Record<Locale, Copy> = { en, ko, ja, zh };
export const benchmarkSharingCopy = (locale: Locale): Copy => copies[locale];
