import type { Locale } from '../../shared/i18n/i18n';
import { benchmarkEnvironmentCopy } from './benchmarkEnvironmentCopy';

const en = {
  publicReview: 'Share result', publicHint: 'Publish this result anonymously on the benchmark website. The summary below shows the main shared model info, hardware, conditions and results; model file paths, launch paths and device identifiers are not included.',
  publicPreview: 'Shared details',
  publicUnknown: 'Details this app could not confirm are shared as unknown rather than guessed.',
  publicInvalid: 'This result cannot be converted for sharing. You can still export it as a file.',
  hydrateLoading: 'Loading the saved share…',
  hydrateError: 'The saved share could not be read. Publishing is turned off so a different result is not sent.',
  shareModel: 'Model', shareHardware: benchmarkEnvironmentCopy.en.hardware, shareRuntime: benchmarkEnvironmentCopy.en.runtime, shareSettings: 'Settings', shareResults: 'Results',
  shareModelName: 'Name', shareModelSize: 'File size', shareUnidentified: 'Not identified', shareOs: 'Operating system', shareAutomatic: benchmarkEnvironmentCopy.en.automatic,
  shareBackend: 'Backend', shareAppVersion: 'App version', shareStatus: 'Status',
  shareInstalledGpus: 'Installed GPUs', shareGpuLayers: benchmarkEnvironmentCopy.en.gpuLayers, shareThreads: benchmarkEnvironmentCopy.en.threads,
  descriptionLockedHint: 'Retries use the original description. After sharing, edit it on the website.',
  historyError: 'History could not be loaded or migrated. Existing records are retained.', historyWarning: 'Some records could not be read or updated. Available results are shown and affected local records are retained.', historyLoading: 'Loading history…', loadMore: 'Load older results',
  identityUnknown: 'Model identity or device selection is incomplete.',
  executionDevice: 'Devices selected for this run', modelHash: 'Model SHA-256',
  localHistoryHint: 'Uploaded results are managed on the website. This device keeps recovery data and recent acknowledged copies. Existing and unuploaded records are retained.',
  localRecovery: 'Stored on this device', localCached: 'Saved on the website · local copy',
  descriptionLabel: 'Description (optional)', descriptionHint: 'Notes shown with the result, such as what you tuned. Paragraphs, lists, http(s) links and code blocks; up to 4,000 characters.',
  descriptionCount: 'Description length',
  publishSelected: 'Publish', cancelPublish: 'Cancel', publishRetry: 'Retry sharing',
  publishPreparing: 'Preparing…', publishSubmitting: 'Publishing…', publishRestoring: 'Checking sharing status…', publishVerifying: 'Complete the verification in your browser…',
  publishRestoreError: 'Sharing status could not be read. Try again.',
  publishServiceLabel: 'Sharing website',
  publishNeedsService: 'Publishing is unavailable because no sharing website is configured.',
  publishBlocked: 'Finish the browser check to publish.',
  publishDeleted: 'This result was deleted on the website, so it will not be published again.',
  publishError: 'Publishing failed. Try again.',
  publishOwnershipMissing: 'This device no longer has edit and delete access for this result. Restore it from a backup in Shared results, then try again.',
  publishAccepted: 'Published. You can edit or delete it from Shared results.',
  legacyConflict: 'This result was already shared in an older format, so a description cannot be added.',
  openManagement: 'Manage on website', retry: 'Retry',
  ownedListTitle: 'Shared results', ownedListHint: 'Choose a result to edit or delete on the website. Saved access connects you directly without entering a key.',
  ownedListEmpty: 'No results shared from this device yet.', ownedListLoadMore: 'Show more', ownedListError: 'Shared results could not be loaded.',
  ownedItemTitle: 'Registered {date}',
  ownedActionError: 'The action could not be completed. Check the file or connection and try again.',
  managementError: 'Could not open result management. Try again.',
  managementOpening: 'Connecting to management…', managementUnavailable: 'This website does not support direct management from the app yet. Try again after the website is updated.', managementDeleted: 'This result has already been deleted from the website.',
  backupTitle: 'Backup and restore',
  backupHint: 'Select a saved backup file on the website to edit or delete its result without typing a key. It also restores access after reinstalling or on another device. Keep the file private.',
  recoveryExport: 'Save backup file', recoveryImport: 'Restore from backup file', recoveryCopy: 'Copy backup code',
  recoverySaved: 'Backup file saved.', recoveryImported: 'Backup restored.', recoveryCopied: 'Backup code copied. Keep it private.',
};
type Copy = { [K in keyof typeof en]: string };
const ko: Copy = {
  publicReview: '결과 공유', publicHint: '이 결과를 벤치마크 웹사이트에 익명으로 게시합니다. 아래 요약에서 공유되는 주요 모델 정보, 하드웨어, 측정 조건과 결과를 확인할 수 있으며, 모델 파일 경로, 실행 경로, 기기 식별 정보는 포함되지 않습니다.',
  publicPreview: '공유되는 정보',
  publicUnknown: '앱에서 확인하지 못한 정보는 추정하지 않고 알 수 없음으로 공유합니다.',
  publicInvalid: '이 결과는 공유 형식으로 변환할 수 없습니다. 파일로 내보내기는 계속 사용할 수 있습니다.',
  hydrateLoading: '저장된 공유 내용을 불러오는 중…',
  hydrateError: '저장된 공유 내용을 읽지 못했습니다. 다른 결과가 전송되지 않도록 게시를 막았습니다.',
  shareModel: '모델', shareHardware: benchmarkEnvironmentCopy.ko.hardware, shareRuntime: benchmarkEnvironmentCopy.ko.runtime, shareSettings: '설정', shareResults: '측정 결과',
  shareModelName: '이름', shareModelSize: '파일 크기', shareUnidentified: '식별되지 않음', shareOs: '운영체제', shareAutomatic: benchmarkEnvironmentCopy.ko.automatic,
  shareBackend: '백엔드', shareAppVersion: '앱 버전', shareStatus: '상태',
  shareInstalledGpus: '설치된 GPU', shareGpuLayers: benchmarkEnvironmentCopy.ko.gpuLayers, shareThreads: benchmarkEnvironmentCopy.ko.threads,
  descriptionLockedHint: '다시 시도할 때는 처음 작성한 설명을 사용합니다. 공유 후에는 웹사이트에서 설명을 수정할 수 있습니다.',
  historyError: '이력을 불러오거나 이전하지 못했습니다. 기존 기록은 유지됩니다.', historyWarning: '일부 기록을 읽거나 갱신하지 못했습니다. 확인 가능한 결과를 표시하며 해당 로컬 기록은 유지됩니다.', historyLoading: '이력 불러오는 중…', loadMore: '이전 결과 더 보기',
  identityUnknown: '모델 식별 또는 사용 장치 정보가 완전하지 않습니다.',
  executionDevice: '이 측정에 선택한 장치', modelHash: '모델 SHA-256',
  localHistoryHint: '업로드한 결과는 웹사이트에서 관리합니다. 앱에는 복구용 데이터와 최근 서버 접수가 확인된 사본을 보관합니다. 기존 기록과 미전송 기록은 유지됩니다.',
  localRecovery: '이 기기에 보관 중', localCached: '웹사이트 저장 확인 · 로컬 사본',
  descriptionLabel: '설명 (선택)', descriptionHint: '조정한 설정 등 결과와 함께 보여줄 메모입니다. 문단, 목록, http(s) 링크, 코드 블록을 사용할 수 있으며 최대 4,000자입니다.',
  descriptionCount: '설명 길이',
  publishSelected: '웹사이트에 공유', cancelPublish: '취소', publishRetry: '공유 다시 시도',
  publishPreparing: '준비 중…', publishSubmitting: '게시 중…', publishRestoring: '공유 상태 확인 중…', publishVerifying: '브라우저에서 확인을 완료해 주세요…',
  publishRestoreError: '공유 상태를 읽지 못했습니다. 다시 시도해 주세요.',
  publishServiceLabel: '공유 웹사이트',
  publishNeedsService: '공유 웹사이트가 설정되지 않아 게시할 수 없습니다.',
  publishBlocked: '게시하려면 브라우저 확인을 완료하세요.',
  publishDeleted: '이 결과는 웹사이트에서 삭제되어 다시 게시하지 않습니다.',
  publishError: '게시하지 못했습니다. 다시 시도하세요.',
  publishOwnershipMissing: '이 기기에 이 결과의 수정·삭제 권한이 없습니다. 공유한 결과 관리에서 백업을 복원한 뒤 다시 시도하세요.',
  publishAccepted: '게시했습니다. 공유한 결과 관리에서 수정하거나 삭제할 수 있습니다.',
  legacyConflict: '이 결과는 이전 형식으로 이미 공유되어 설명을 추가할 수 없습니다.',
  openManagement: '웹사이트에서 관리', retry: '다시 시도',
  ownedListTitle: '공유한 결과 관리', ownedListHint: '수정·삭제할 결과를 선택하세요. 저장된 관리 권한으로 웹사이트에 바로 연결되므로 키를 입력할 필요가 없습니다.',
  ownedListEmpty: '이 기기에서 공유한 결과가 없습니다.', ownedListLoadMore: '더 보기', ownedListError: '공유한 결과를 불러오지 못했습니다.',
  ownedItemTitle: '{date} 등록',
  ownedActionError: '작업을 완료하지 못했습니다. 파일이나 연결을 확인하고 다시 시도하세요.',
  managementError: '결과 관리 페이지를 열지 못했습니다. 다시 시도해 주세요.',
  managementOpening: '관리 화면 연결 중…', managementUnavailable: '이 웹사이트는 아직 앱에서 바로 관리하는 기능을 지원하지 않습니다. 웹사이트 업데이트 후 다시 시도해 주세요.', managementDeleted: '웹사이트에서 이미 삭제된 결과입니다.',
  backupTitle: '백업 및 복원',
  backupHint: '저장한 백업 파일을 웹사이트에서 선택하면 키 입력 없이 결과를 수정·삭제할 수 있습니다. 앱을 다시 설치하거나 기기를 바꿀 때도 권한을 복원할 수 있습니다. 파일은 다른 사람과 공유하지 마세요.',
  recoveryExport: '백업 파일 저장', recoveryImport: '백업 파일에서 복원', recoveryCopy: '백업 코드 복사',
  recoverySaved: '백업 파일을 저장했습니다.', recoveryImported: '백업을 복원했습니다.', recoveryCopied: '백업 코드를 복사했습니다. 다른 사람과 공유하지 마세요.',
};
const ja: Copy = {
  publicReview: '結果を共有', publicHint: 'この結果をベンチマークサイトに匿名で公開します。以下の概要で共有される主なモデル情報、ハードウェア、測定条件と結果を確認できます。モデルファイルのパス、起動パス、デバイス識別子は含まれません。',
  publicPreview: '共有される情報',
  publicUnknown: 'アプリで確認できなかった情報は推定せず、不明として共有します。',
  publicInvalid: 'この結果は共有形式に変換できません。ファイルへの書き出しは引き続き利用できます。',
  hydrateLoading: '保存済みの共有内容を読み込み中…',
  hydrateError: '保存済みの共有内容を読み込めませんでした。異なる結果を送信しないよう、公開を停止しました。',
  shareModel: 'モデル', shareHardware: benchmarkEnvironmentCopy.ja.hardware, shareRuntime: benchmarkEnvironmentCopy.ja.runtime, shareSettings: '設定', shareResults: '測定結果',
  shareModelName: '名前', shareModelSize: 'ファイルサイズ', shareUnidentified: '未識別', shareOs: 'OS', shareAutomatic: benchmarkEnvironmentCopy.ja.automatic,
  shareBackend: 'バックエンド', shareAppVersion: 'アプリバージョン', shareStatus: '状態',
  shareInstalledGpus: '搭載GPU', shareGpuLayers: benchmarkEnvironmentCopy.ja.gpuLayers, shareThreads: benchmarkEnvironmentCopy.ja.threads,
  descriptionLockedHint: '再試行には最初の説明を使用します。共有後の説明はウェブサイトで編集できます。',
  historyError: '履歴の読み込みまたは移行に失敗しました。既存の記録は保持されています。', historyWarning: '一部の記録を読み込みまたは更新できませんでした。利用できる結果を表示し、該当するローカル記録は保持しています。', historyLoading: '履歴を読み込み中…', loadMore: '以前の結果を読み込む',
  identityUnknown: 'モデル識別またはデバイス選択情報が不完全です。',
  executionDevice: 'この測定で選択したデバイス', modelHash: 'モデルSHA-256',
  localHistoryHint: 'アップロードした結果はウェブサイトで管理します。このデバイスには復旧用データと、受理された最近のコピーを保持します。既存および未送信の記録は保持します。',
  localRecovery: 'このデバイスに保存', localCached: 'ウェブサイトに保存済み · ローカルコピー',
  descriptionLabel: '説明（任意）', descriptionHint: '調整した設定など、結果と一緒に表示するメモです。段落、リスト、http(s)リンク、コードブロックを使用でき、最大4,000文字です。',
  descriptionCount: '説明の長さ',
  publishSelected: '公開', cancelPublish: 'キャンセル', publishRetry: '共有を再試行',
  publishPreparing: '準備中…', publishSubmitting: '公開中…', publishRestoring: '共有状態を確認中…', publishVerifying: 'ブラウザでの確認を完了してください…',
  publishRestoreError: '共有状態を読み込めませんでした。もう一度お試しください。',
  publishServiceLabel: '共有サイト',
  publishNeedsService: '共有サイトが設定されていないため公開できません。',
  publishBlocked: '公開するにはブラウザでの確認を完了してください。',
  publishDeleted: 'この結果はウェブサイトで削除されたため、再公開しません。',
  publishError: '公開できませんでした。もう一度お試しください。',
  publishOwnershipMissing: 'このデバイスにはこの結果の編集・削除権限がありません。共有した結果の管理でバックアップを復元してから再試行してください。',
  publishAccepted: '公開しました。共有した結果の管理から編集・削除できます。',
  legacyConflict: 'この結果は旧形式で共有済みのため、説明を追加できません。',
  openManagement: 'ウェブサイトで管理', retry: '再試行',
  ownedListTitle: '共有した結果の管理', ownedListHint: '編集・削除する結果を選択してください。保存された管理権限でウェブサイトに直接接続するため、キーの入力は不要です。',
  ownedListEmpty: 'このデバイスから共有した結果はありません。', ownedListLoadMore: 'さらに表示', ownedListError: '共有した結果を読み込めませんでした。',
  ownedItemTitle: '{date} に登録',
  ownedActionError: '操作を完了できませんでした。ファイルまたは接続を確認して再試行してください。',
  managementError: '結果管理ページを開けませんでした。もう一度お試しください。',
  managementOpening: '管理画面に接続中…', managementUnavailable: 'このウェブサイトはアプリからの直接管理にまだ対応していません。ウェブサイトの更新後にもう一度お試しください。', managementDeleted: 'この結果はウェブサイトから削除済みです。',
  backupTitle: 'バックアップと復元',
  backupHint: '保存したバックアップファイルをウェブサイトで選択すると、キーを入力せずに結果を編集・削除できます。再インストール後や別のデバイスでも権限を復元できます。ファイルは他人と共有しないでください。',
  recoveryExport: 'バックアップファイルを保存', recoveryImport: 'バックアップファイルから復元', recoveryCopy: 'バックアップコードをコピー',
  recoverySaved: 'バックアップファイルを保存しました。', recoveryImported: 'バックアップを復元しました。', recoveryCopied: 'バックアップコードをコピーしました。他人と共有しないでください。',
};
const zh: Copy = {
  publicReview: '分享结果', publicHint: '将此结果匿名发布到基准测试网站。下方的摘要显示了将分享的主要模型信息、硬件、测试条件和结果；不包含模型文件路径、启动路径或设备标识符。',
  publicPreview: '将分享的信息',
  publicUnknown: '应用无法确认的信息将按未知分享，不做推测。',
  publicInvalid: '无法将此结果转换为分享格式。仍可将其导出为文件。',
  hydrateLoading: '正在加载已保存的分享内容…',
  hydrateError: '无法读取已保存的分享内容。已停止发布，以免发送不同的结果。',
  shareModel: '模型', shareHardware: benchmarkEnvironmentCopy.zh.hardware, shareRuntime: benchmarkEnvironmentCopy.zh.runtime, shareSettings: '设置', shareResults: '测量结果',
  shareModelName: '名称', shareModelSize: '文件大小', shareUnidentified: '未识别', shareOs: '操作系统', shareAutomatic: benchmarkEnvironmentCopy.zh.automatic,
  shareBackend: '后端', shareAppVersion: '应用版本', shareStatus: '状态',
  shareInstalledGpus: '已安装GPU', shareGpuLayers: benchmarkEnvironmentCopy.zh.gpuLayers, shareThreads: benchmarkEnvironmentCopy.zh.threads,
  descriptionLockedHint: '重试会使用最初的说明。分享后可在网站上编辑说明。',
  historyError: '无法加载或迁移历史记录。已有记录保持不变。', historyWarning: '部分记录无法读取或更新。显示可用的结果，相关本地记录保持不变。', historyLoading: '正在加载历史…', loadMore: '加载更早的结果',
  identityUnknown: '模型标识或设备选择信息不完整。',
  executionDevice: '本次测试选择的设备', modelHash: '模型SHA-256',
  localHistoryHint: '已上传的结果由网站管理。此设备保留恢复数据和最近服务器已确认的副本。已有和未发送的记录会保留。',
  localRecovery: '保存在此设备', localCached: '网站已保存 · 本地副本',
  descriptionLabel: '说明（可选）', descriptionHint: '与结果一起显示的备注，例如调整过的设置。支持段落、列表、http(s)链接和代码块，最多4,000字符。',
  descriptionCount: '说明长度',
  publishSelected: '发布', cancelPublish: '取消', publishRetry: '重试分享',
  publishPreparing: '准备中…', publishSubmitting: '正在发布…', publishRestoring: '正在检查分享状态…', publishVerifying: '请在浏览器中完成验证…',
  publishRestoreError: '无法读取分享状态。请重试。',
  publishServiceLabel: '分享网站',
  publishNeedsService: '未配置分享网站，无法发布。',
  publishBlocked: '请完成浏览器验证后再发布。',
  publishDeleted: '该结果已在网站上删除，不会再次发布。',
  publishError: '发布失败。请重试。',
  publishOwnershipMissing: '此设备已没有该结果的编辑和删除权限。请在“已分享结果管理”中从备份恢复后重试。',
  publishAccepted: '已发布。可在“已分享结果管理”中编辑或删除。',
  legacyConflict: '该结果已用旧格式分享，无法添加说明。',
  openManagement: '在网站上管理', retry: '重试',
  ownedListTitle: '已分享结果管理', ownedListHint: '选择要编辑或删除的结果。使用已保存的管理权限直接连接网站，无需输入密钥。',
  ownedListEmpty: '此设备尚未分享任何结果。', ownedListLoadMore: '显示更多', ownedListError: '无法加载已分享的结果。',
  ownedItemTitle: '{date} 注册',
  ownedActionError: '无法完成操作。请检查文件或网络连接后重试。',
  managementError: '无法打开结果管理页面。请重试。',
  managementOpening: '正在连接管理页面…', managementUnavailable: '此网站暂不支持从应用直接管理。请在网站更新后重试。', managementDeleted: '此结果已从网站删除。',
  backupTitle: '备份与恢复',
  backupHint: '在网站上选择已保存的备份文件，即可编辑或删除对应结果，无需输入密钥。重新安装应用或更换设备后也可恢复权限。请勿与他人分享此文件。',
  recoveryExport: '保存备份文件', recoveryImport: '从备份文件恢复', recoveryCopy: '复制备份代码',
  recoverySaved: '已保存备份文件。', recoveryImported: '已恢复备份。', recoveryCopied: '已复制备份代码。请勿与他人分享。',
};
const copies: Record<Locale, Copy> = { en, ko, ja, zh };
export const benchmarkSharingCopy = (locale: Locale): Copy => copies[locale];
